/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) px4_payload_model_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {16, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {14, 1, 1};
static const casadi_int casadi_s3[3] = {20, 1, 1};

/* px4_payload_model_expl_vde_adj:(i0[16],i1[16],i2[4],i3[14])->(o0[20]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[0]? arg[0][12] : 0;
  a01=casadi_sq(a00);
  a02=arg[0]? arg[0][13] : 0;
  a03=casadi_sq(a02);
  a01=(a01-a03);
  a03=arg[0]? arg[0][14] : 0;
  a04=casadi_sq(a03);
  a01=(a01-a04);
  a04=arg[0]? arg[0][15] : 0;
  a05=casadi_sq(a04);
  a01=(a01+a05);
  a05=arg[2]? arg[2][0] : 0;
  a06=4.7732696897374699e-01;
  a07=arg[1]? arg[1][10] : 0;
  a07=(a06*a07);
  a08=(a05*a07);
  a09=(a01*a08);
  a10=2.;
  a11=(a03*a04);
  a12=(a00*a02);
  a11=(a11-a12);
  a11=(a10*a11);
  a12=arg[1]? arg[1][11] : 0;
  a12=(a06*a12);
  a13=(a05*a12);
  a14=(a11*a13);
  a09=(a09-a14);
  a14=arg[0]? arg[0][10] : 0;
  a15=arg[1]? arg[1][8] : 0;
  a16=(a14*a15);
  a09=(a09-a16);
  a16=arg[0]? arg[0][11] : 0;
  a17=arg[1]? arg[1][7] : 0;
  a18=(a16*a17);
  a09=(a09+a18);
  a18=2.0950000000000002e+00;
  a19=arg[0]? arg[0][9] : 0;
  a20=casadi_sq(a19);
  a21=casadi_sq(a14);
  a20=(a20+a21);
  a21=casadi_sq(a16);
  a20=(a20+a21);
  a20=(a18*a20);
  a21=3.8535645472061653e-01;
  a22=arg[1]? arg[1][3] : 0;
  a22=(a21*a22);
  a23=(a20*a22);
  a09=(a09-a23);
  a23=arg[0]? arg[0][6] : 0;
  a24=(a02*a04);
  a25=(a00*a03);
  a24=(a24+a25);
  a24=(a10*a24);
  a25=(a05*a24);
  a26=(a23*a25);
  a27=arg[0]? arg[0][7] : 0;
  a28=(a05*a11);
  a29=(a27*a28);
  a26=(a26+a29);
  a29=arg[0]? arg[0][8] : 0;
  a30=(a05*a01);
  a31=(a29*a30);
  a26=(a26+a31);
  a31=(a26*a22);
  a09=(a09+a31);
  a31=arg[1]? arg[1][5] : 0;
  a31=(a21*a31);
  a32=(a29*a31);
  a33=arg[1]? arg[1][4] : 0;
  a21=(a21*a33);
  a33=(a27*a21);
  a32=(a32+a33);
  a22=(a23*a22);
  a32=(a32+a22);
  a25=(a25*a32);
  a09=(a09+a25);
  if (res[0]!=0) res[0][6]=a09;
  a09=(a24*a13);
  a25=arg[1]? arg[1][9] : 0;
  a06=(a06*a25);
  a25=(a05*a06);
  a22=(a01*a25);
  a09=(a09-a22);
  a22=(a19*a15);
  a09=(a09+a22);
  a22=arg[1]? arg[1][6] : 0;
  a33=(a16*a22);
  a09=(a09-a33);
  a33=(a20*a21);
  a09=(a09-a33);
  a21=(a26*a21);
  a09=(a09+a21);
  a28=(a28*a32);
  a09=(a09+a28);
  if (res[0]!=0) res[0][7]=a09;
  a09=(a11*a25);
  a28=(a24*a08);
  a09=(a09-a28);
  a28=(a19*a17);
  a09=(a09-a28);
  a28=(a14*a22);
  a09=(a09+a28);
  a20=(a20*a31);
  a09=(a09-a20);
  a26=(a26*a31);
  a09=(a09+a26);
  a30=(a30*a32);
  a09=(a09+a30);
  if (res[0]!=0) res[0][8]=a09;
  a09=(a27*a15);
  a30=(a29*a17);
  a09=(a09-a30);
  a19=(a19+a19);
  a18=(a18*a32);
  a19=(a19*a18);
  a09=(a09-a19);
  if (res[0]!=0) res[0][9]=a09;
  a09=(a29*a22);
  a15=(a23*a15);
  a09=(a09-a15);
  a14=(a14+a14);
  a14=(a14*a18);
  a09=(a09-a14);
  if (res[0]!=0) res[0][10]=a09;
  a17=(a23*a17);
  a22=(a27*a22);
  a17=(a17-a22);
  a16=(a16+a16);
  a16=(a16*a18);
  a17=(a17-a16);
  if (res[0]!=0) res[0][11]=a17;
  a17=arg[2]? arg[2][3] : 0;
  a16=5.0000000000000000e-01;
  a18=arg[1]? arg[1][15] : 0;
  a18=(a16*a18);
  a22=(a17*a18);
  a09=arg[2]? arg[2][2] : 0;
  a14=arg[1]? arg[1][14] : 0;
  a14=(a16*a14);
  a15=(a09*a14);
  a22=(a22+a15);
  a15=arg[2]? arg[2][1] : 0;
  a19=arg[1]? arg[1][13] : 0;
  a19=(a16*a19);
  a30=(a15*a19);
  a22=(a22+a30);
  a30=(a00+a00);
  a26=(a23*a08);
  a31=(a27*a25);
  a26=(a26-a31);
  a31=(a29*a32);
  a20=(a05*a31);
  a26=(a26+a20);
  a30=(a30*a26);
  a22=(a22+a30);
  a25=(a29*a25);
  a30=(a23*a13);
  a25=(a25-a30);
  a30=(a27*a32);
  a20=(a05*a30);
  a25=(a25+a20);
  a25=(a10*a25);
  a20=(a02*a25);
  a22=(a22-a20);
  a13=(a27*a13);
  a08=(a29*a08);
  a13=(a13-a08);
  a32=(a23*a32);
  a05=(a05*a32);
  a13=(a13+a05);
  a10=(a10*a13);
  a13=(a03*a10);
  a22=(a22+a13);
  if (res[0]!=0) res[0][12]=a22;
  a22=(a09*a18);
  a13=(a17*a14);
  a22=(a22-a13);
  a13=arg[1]? arg[1][12] : 0;
  a16=(a16*a13);
  a13=(a15*a16);
  a22=(a22-a13);
  a13=(a02+a02);
  a13=(a13*a26);
  a22=(a22-a13);
  a13=(a00*a25);
  a22=(a22-a13);
  a13=(a04*a10);
  a22=(a22+a13);
  if (res[0]!=0) res[0][13]=a22;
  a22=(a17*a19);
  a13=(a15*a18);
  a22=(a22-a13);
  a13=(a09*a16);
  a22=(a22-a13);
  a13=(a03+a03);
  a13=(a13*a26);
  a22=(a22-a13);
  a13=(a04*a25);
  a22=(a22+a13);
  a13=(a00*a10);
  a22=(a22+a13);
  if (res[0]!=0) res[0][14]=a22;
  a15=(a15*a14);
  a09=(a09*a19);
  a15=(a15-a09);
  a17=(a17*a16);
  a15=(a15-a17);
  a17=(a04+a04);
  a17=(a17*a26);
  a15=(a15+a17);
  a25=(a03*a25);
  a15=(a15+a25);
  a10=(a02*a10);
  a15=(a15+a10);
  if (res[0]!=0) res[0][15]=a15;
  a31=(a01*a31);
  a15=(a23*a11);
  a10=(a27*a24);
  a15=(a15-a10);
  a15=(a15*a12);
  a12=(a29*a24);
  a23=(a23*a01);
  a12=(a12-a23);
  a12=(a12*a07);
  a15=(a15+a12);
  a27=(a27*a01);
  a29=(a29*a11);
  a27=(a27-a29);
  a27=(a27*a06);
  a15=(a15+a27);
  a31=(a31-a15);
  a11=(a11*a30);
  a31=(a31+a11);
  a24=(a24*a32);
  a31=(a31+a24);
  if (res[0]!=0) res[0][16]=a31;
  a31=(a04*a14);
  a24=(a03*a18);
  a31=(a31-a24);
  a24=(a00*a19);
  a31=(a31+a24);
  a24=(a02*a16);
  a31=(a31-a24);
  if (res[0]!=0) res[0][17]=a31;
  a31=(a02*a18);
  a24=(a00*a14);
  a31=(a31+a24);
  a24=(a04*a19);
  a31=(a31-a24);
  a24=(a03*a16);
  a31=(a31-a24);
  if (res[0]!=0) res[0][18]=a31;
  a00=(a00*a18);
  a02=(a02*a14);
  a00=(a00-a02);
  a03=(a03*a19);
  a00=(a00+a03);
  a04=(a04*a16);
  a00=(a00-a04);
  if (res[0]!=0) res[0][19]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int px4_payload_model_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int px4_payload_model_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int px4_payload_model_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void px4_payload_model_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int px4_payload_model_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void px4_payload_model_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void px4_payload_model_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void px4_payload_model_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int px4_payload_model_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int px4_payload_model_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real px4_payload_model_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* px4_payload_model_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* px4_payload_model_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* px4_payload_model_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* px4_payload_model_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int px4_payload_model_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int px4_payload_model_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
