/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) kinodynamic_load_2cables_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {41, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};

/* kinodynamic_load_2cables_expl_ode_fun:(i0[41],i1[8],i2[0])->(o0[41]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33;
  a00=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[0]? arg[0][25] : 0;
  a01=arg[0]? arg[0][13] : 0;
  a02=(a00*a01);
  a03=arg[0]? arg[0][39] : 0;
  a04=arg[0]? arg[0][27] : 0;
  a05=(a03*a04);
  a02=(a02+a05);
  a02=(-a02);
  if (res[0]!=0) res[0][3]=a02;
  a02=arg[0]? arg[0][14] : 0;
  a05=(a00*a02);
  a06=arg[0]? arg[0][28] : 0;
  a07=(a03*a06);
  a05=(a05+a07);
  a05=(-a05);
  if (res[0]!=0) res[0][4]=a05;
  a05=-9.8100000000000005e+00;
  a07=arg[0]? arg[0][15] : 0;
  a08=(a00*a07);
  a09=arg[0]? arg[0][29] : 0;
  a10=(a03*a09);
  a08=(a08+a10);
  a05=(a05-a08);
  if (res[0]!=0) res[0][5]=a05;
  a05=5.0000000000000000e-01;
  a08=arg[0]? arg[0][7] : 0;
  a10=arg[0]? arg[0][10] : 0;
  a11=(a08*a10);
  a12=arg[0]? arg[0][8] : 0;
  a13=arg[0]? arg[0][11] : 0;
  a14=(a12*a13);
  a11=(a11+a14);
  a14=arg[0]? arg[0][9] : 0;
  a15=arg[0]? arg[0][12] : 0;
  a16=(a14*a15);
  a11=(a11+a16);
  a11=(a05*a11);
  a11=(-a11);
  if (res[0]!=0) res[0][6]=a11;
  a11=arg[0]? arg[0][6] : 0;
  a16=(a11*a10);
  a17=(a14*a13);
  a16=(a16-a17);
  a17=(a12*a15);
  a16=(a16+a17);
  a16=(a05*a16);
  if (res[0]!=0) res[0][7]=a16;
  a16=(a14*a10);
  a17=(a11*a13);
  a16=(a16+a17);
  a17=(a08*a15);
  a16=(a16-a17);
  a16=(a05*a16);
  if (res[0]!=0) res[0][8]=a16;
  a16=(a08*a13);
  a17=(a12*a10);
  a16=(a16-a17);
  a17=(a11*a15);
  a16=(a16+a17);
  a05=(a05*a16);
  if (res[0]!=0) res[0][9]=a05;
  a05=20.;
  a16=8.0000000000000002e-02;
  a16=(a16*a15);
  a17=(a13*a16);
  a18=5.0000000000000003e-02;
  a19=(a18*a13);
  a20=(a15*a19);
  a17=(a17-a20);
  a20=3.6739403974420595e-17;
  a21=2.;
  a22=(a08*a14);
  a23=(a11*a12);
  a24=(a22+a23);
  a24=(a21*a24);
  a25=(a24*a04);
  a26=(a12*a14);
  a27=(a11*a08);
  a28=(a26-a27);
  a28=(a21*a28);
  a29=(a28*a06);
  a25=(a25+a29);
  a29=1.;
  a30=casadi_sq(a08);
  a31=casadi_sq(a12);
  a32=(a30+a31);
  a32=(a21*a32);
  a32=(a29-a32);
  a33=(a32*a09);
  a25=(a25+a33);
  a33=(a20*a25);
  a33=(a03*a33);
  a17=(a17+a33);
  a17=(a05*a17);
  a17=(-a17);
  if (res[0]!=0) res[0][10]=a17;
  a17=2.9999999999999999e-01;
  a24=(a24*a01);
  a28=(a28*a02);
  a24=(a24+a28);
  a32=(a32*a07);
  a24=(a24+a32);
  a24=(a17*a24);
  a24=(a00*a24);
  a32=-2.9999999999999999e-01;
  a25=(a32*a25);
  a25=(a03*a25);
  a24=(a24+a25);
  a18=(a18*a10);
  a15=(a15*a18);
  a16=(a10*a16);
  a15=(a15-a16);
  a24=(a24-a15);
  a05=(a05*a24);
  if (res[0]!=0) res[0][11]=a05;
  a05=1.2500000000000000e+01;
  a24=casadi_sq(a14);
  a31=(a31+a24);
  a31=(a21*a31);
  a31=(a29-a31);
  a31=(a31*a04);
  a08=(a08*a12);
  a11=(a11*a14);
  a14=(a08+a11);
  a14=(a21*a14);
  a14=(a14*a06);
  a31=(a31+a14);
  a22=(a22-a23);
  a22=(a21*a22);
  a22=(a22*a09);
  a31=(a31+a22);
  a20=(a20*a31);
  a08=(a08-a11);
  a08=(a21*a08);
  a11=(a08*a04);
  a30=(a30+a24);
  a30=(a21*a30);
  a29=(a29-a30);
  a30=(a29*a06);
  a11=(a11+a30);
  a26=(a26+a27);
  a21=(a21*a26);
  a26=(a21*a09);
  a11=(a11+a26);
  a32=(a32*a11);
  a20=(a20-a32);
  a03=(a03*a20);
  a08=(a08*a01);
  a29=(a29*a02);
  a08=(a08+a29);
  a21=(a21*a07);
  a08=(a08+a21);
  a17=(a17*a08);
  a00=(a00*a17);
  a03=(a03-a00);
  a10=(a10*a19);
  a13=(a13*a18);
  a10=(a10-a13);
  a03=(a03-a10);
  a05=(a05*a03);
  if (res[0]!=0) res[0][12]=a05;
  a05=arg[0]? arg[0][17] : 0;
  a03=(a05*a07);
  a10=arg[0]? arg[0][18] : 0;
  a13=(a10*a02);
  a03=(a03-a13);
  if (res[0]!=0) res[0][13]=a03;
  a10=(a10*a01);
  a03=arg[0]? arg[0][16] : 0;
  a07=(a03*a07);
  a10=(a10-a07);
  if (res[0]!=0) res[0][14]=a10;
  a03=(a03*a02);
  a05=(a05*a01);
  a03=(a03-a05);
  if (res[0]!=0) res[0][15]=a03;
  a03=arg[0]? arg[0][19] : 0;
  if (res[0]!=0) res[0][16]=a03;
  a03=arg[0]? arg[0][20] : 0;
  if (res[0]!=0) res[0][17]=a03;
  a03=arg[0]? arg[0][21] : 0;
  if (res[0]!=0) res[0][18]=a03;
  a03=arg[0]? arg[0][22] : 0;
  if (res[0]!=0) res[0][19]=a03;
  a03=arg[0]? arg[0][23] : 0;
  if (res[0]!=0) res[0][20]=a03;
  a03=arg[0]? arg[0][24] : 0;
  if (res[0]!=0) res[0][21]=a03;
  a03=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][22]=a03;
  a03=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][23]=a03;
  a03=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][24]=a03;
  a03=arg[0]? arg[0][26] : 0;
  if (res[0]!=0) res[0][25]=a03;
  a03=arg[1]? arg[1][3] : 0;
  if (res[0]!=0) res[0][26]=a03;
  a03=arg[0]? arg[0][31] : 0;
  a05=(a03*a09);
  a01=arg[0]? arg[0][32] : 0;
  a02=(a01*a06);
  a05=(a05-a02);
  if (res[0]!=0) res[0][27]=a05;
  a01=(a01*a04);
  a05=arg[0]? arg[0][30] : 0;
  a09=(a05*a09);
  a01=(a01-a09);
  if (res[0]!=0) res[0][28]=a01;
  a05=(a05*a06);
  a03=(a03*a04);
  a05=(a05-a03);
  if (res[0]!=0) res[0][29]=a05;
  a05=arg[0]? arg[0][33] : 0;
  if (res[0]!=0) res[0][30]=a05;
  a05=arg[0]? arg[0][34] : 0;
  if (res[0]!=0) res[0][31]=a05;
  a05=arg[0]? arg[0][35] : 0;
  if (res[0]!=0) res[0][32]=a05;
  a05=arg[0]? arg[0][36] : 0;
  if (res[0]!=0) res[0][33]=a05;
  a05=arg[0]? arg[0][37] : 0;
  if (res[0]!=0) res[0][34]=a05;
  a05=arg[0]? arg[0][38] : 0;
  if (res[0]!=0) res[0][35]=a05;
  a05=arg[1]? arg[1][4] : 0;
  if (res[0]!=0) res[0][36]=a05;
  a05=arg[1]? arg[1][5] : 0;
  if (res[0]!=0) res[0][37]=a05;
  a05=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][38]=a05;
  a05=arg[0]? arg[0][40] : 0;
  if (res[0]!=0) res[0][39]=a05;
  a05=arg[1]? arg[1][7] : 0;
  if (res[0]!=0) res[0][40]=a05;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_2cables_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_2cables_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_2cables_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinodynamic_load_2cables_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_2cables_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinodynamic_load_2cables_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void kinodynamic_load_2cables_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void kinodynamic_load_2cables_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int kinodynamic_load_2cables_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int kinodynamic_load_2cables_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real kinodynamic_load_2cables_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinodynamic_load_2cables_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinodynamic_load_2cables_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinodynamic_load_2cables_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinodynamic_load_2cables_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_2cables_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_2cables_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
