/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) kinodynamic_load_2cables_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {41, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {49, 1, 1};

/* kinodynamic_load_2cables_expl_vde_adj:(i0[41],i1[41],i2[8],i3[0])->(o0[49]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[0]? arg[0][9] : 0;
  a01=2.;
  a02=arg[0]? arg[0][13] : 0;
  a03=2.9999999999999999e-01;
  a04=arg[0]? arg[0][25] : 0;
  a05=1.2500000000000000e+01;
  a06=arg[1]? arg[1][12] : 0;
  a05=(a05*a06);
  a06=(a04*a05);
  a06=(a03*a06);
  a07=(a02*a06);
  a08=arg[0]? arg[0][27] : 0;
  a09=-2.9999999999999999e-01;
  a10=arg[0]? arg[0][39] : 0;
  a11=(a10*a05);
  a12=(a09*a11);
  a13=(a08*a12);
  a07=(a07+a13);
  a07=(a01*a07);
  a13=(a00*a07);
  a14=arg[0]? arg[0][7] : 0;
  a15=arg[0]? arg[0][15] : 0;
  a16=(a15*a06);
  a17=arg[0]? arg[0][29] : 0;
  a18=(a17*a12);
  a16=(a16+a18);
  a16=(a01*a16);
  a18=(a14*a16);
  a13=(a13-a18);
  a18=arg[0]? arg[0][8] : 0;
  a19=3.6739403974420595e-17;
  a11=(a19*a11);
  a20=(a17*a11);
  a20=(a01*a20);
  a21=(a18*a20);
  a13=(a13-a21);
  a21=arg[0]? arg[0][28] : 0;
  a22=(a21*a11);
  a22=(a01*a22);
  a23=(a00*a22);
  a13=(a13+a23);
  a23=arg[0]? arg[0][14] : 0;
  a24=20.;
  a25=arg[1]? arg[1][11] : 0;
  a25=(a24*a25);
  a26=(a04*a25);
  a26=(a03*a26);
  a27=(a23*a26);
  a28=(a10*a25);
  a28=(a09*a28);
  a29=arg[1]? arg[1][10] : 0;
  a24=(a24*a29);
  a29=(a10*a24);
  a29=(a19*a29);
  a28=(a28-a29);
  a29=(a21*a28);
  a27=(a27+a29);
  a27=(a01*a27);
  a29=(a14*a27);
  a13=(a13-a29);
  a29=(a02*a26);
  a30=(a08*a28);
  a29=(a29+a30);
  a29=(a01*a29);
  a30=(a18*a29);
  a13=(a13+a30);
  a30=arg[0]? arg[0][12] : 0;
  a31=5.0000000000000000e-01;
  a32=arg[1]? arg[1][9] : 0;
  a32=(a31*a32);
  a33=(a30*a32);
  a13=(a13+a33);
  a33=arg[0]? arg[0][11] : 0;
  a34=arg[1]? arg[1][8] : 0;
  a34=(a31*a34);
  a35=(a33*a34);
  a13=(a13+a35);
  a35=arg[0]? arg[0][10] : 0;
  a36=arg[1]? arg[1][7] : 0;
  a36=(a31*a36);
  a37=(a35*a36);
  a13=(a13+a37);
  if (res[0]!=0) res[0][6]=a13;
  a13=(a14+a14);
  a37=(a23*a06);
  a38=(a21*a12);
  a37=(a37+a38);
  a37=(a01*a37);
  a38=(a13*a37);
  a39=arg[0]? arg[0][6] : 0;
  a40=(a39*a16);
  a38=(a38-a40);
  a40=(a18*a07);
  a38=(a38-a40);
  a40=(a00*a20);
  a38=(a38+a40);
  a40=(a18*a22);
  a38=(a38+a40);
  a40=(a15*a26);
  a41=(a17*a28);
  a40=(a40+a41);
  a40=(a01*a40);
  a13=(a13*a40);
  a38=(a38-a13);
  a13=(a39*a27);
  a38=(a38-a13);
  a13=(a00*a29);
  a38=(a38+a13);
  a13=(a33*a32);
  a38=(a38+a13);
  a13=(a30*a34);
  a38=(a38-a13);
  a13=arg[1]? arg[1][6] : 0;
  a31=(a31*a13);
  a13=(a35*a31);
  a38=(a38-a13);
  if (res[0]!=0) res[0][7]=a38;
  a38=(a14*a22);
  a13=(a00*a16);
  a41=(a14*a07);
  a13=(a13+a41);
  a41=(a39*a20);
  a13=(a13+a41);
  a38=(a38-a13);
  a13=(a18+a18);
  a41=(a08*a11);
  a41=(a01*a41);
  a42=(a13*a41);
  a38=(a38-a42);
  a13=(a13*a40);
  a38=(a38-a13);
  a13=(a00*a27);
  a38=(a38+a13);
  a13=(a39*a29);
  a38=(a38+a13);
  a13=(a35*a32);
  a38=(a38-a13);
  a13=(a30*a36);
  a38=(a38+a13);
  a13=(a33*a31);
  a38=(a38-a13);
  if (res[0]!=0) res[0][8]=a38;
  a38=(a00+a00);
  a37=(a38*a37);
  a16=(a18*a16);
  a37=(a37-a16);
  a07=(a39*a07);
  a37=(a37+a07);
  a20=(a14*a20);
  a37=(a37+a20);
  a22=(a39*a22);
  a37=(a37+a22);
  a38=(a38*a41);
  a37=(a37-a38);
  a27=(a18*a27);
  a37=(a37+a27);
  a29=(a14*a29);
  a37=(a37+a29);
  a29=(a35*a34);
  a37=(a37+a29);
  a29=(a33*a36);
  a37=(a37-a29);
  a29=(a30*a31);
  a37=(a37-a29);
  if (res[0]!=0) res[0][9]=a37;
  a37=8.0000000000000002e-02;
  a29=(a37*a30);
  a27=(a29*a25);
  a38=5.0000000000000003e-02;
  a41=(a38*a33);
  a22=(a41*a05);
  a27=(a27-a22);
  a22=(a33*a05);
  a20=(a30*a25);
  a22=(a22-a20);
  a22=(a38*a22);
  a27=(a27+a22);
  a22=(a18*a32);
  a27=(a27-a22);
  a22=(a00*a34);
  a27=(a27+a22);
  a22=(a39*a36);
  a27=(a27+a22);
  a22=(a14*a31);
  a27=(a27-a22);
  if (res[0]!=0) res[0][10]=a27;
  a27=(a38*a35);
  a22=(a27*a05);
  a30=(a30*a24);
  a20=(a35*a05);
  a30=(a30-a20);
  a38=(a38*a30);
  a22=(a22+a38);
  a29=(a29*a24);
  a22=(a22-a29);
  a29=(a14*a32);
  a22=(a22+a29);
  a29=(a39*a34);
  a22=(a22+a29);
  a29=(a00*a36);
  a22=(a22-a29);
  a29=(a18*a31);
  a22=(a22-a29);
  if (res[0]!=0) res[0][11]=a22;
  a41=(a41*a24);
  a27=(a27*a25);
  a41=(a41-a27);
  a35=(a35*a25);
  a33=(a33*a24);
  a35=(a35-a33);
  a37=(a37*a35);
  a41=(a41+a37);
  a32=(a39*a32);
  a41=(a41+a32);
  a34=(a14*a34);
  a41=(a41-a34);
  a36=(a18*a36);
  a41=(a41+a36);
  a31=(a00*a31);
  a41=(a41-a31);
  if (res[0]!=0) res[0][12]=a41;
  a41=arg[0]? arg[0][18] : 0;
  a31=arg[1]? arg[1][14] : 0;
  a36=(a41*a31);
  a34=arg[0]? arg[0][17] : 0;
  a32=arg[1]? arg[1][15] : 0;
  a37=(a34*a32);
  a36=(a36-a37);
  a37=(a14*a18);
  a35=(a39*a00);
  a33=(a37-a35);
  a33=(a01*a33);
  a27=(a33*a06);
  a36=(a36-a27);
  a27=(a14*a00);
  a22=(a39*a18);
  a29=(a27+a22);
  a29=(a01*a29);
  a38=(a29*a26);
  a36=(a36+a38);
  a38=arg[1]? arg[1][3] : 0;
  a30=(a04*a38);
  a36=(a36-a30);
  if (res[0]!=0) res[0][13]=a36;
  a36=arg[0]? arg[0][16] : 0;
  a30=(a36*a32);
  a20=arg[1]? arg[1][13] : 0;
  a41=(a41*a20);
  a30=(a30-a41);
  a41=1.;
  a07=casadi_sq(a14);
  a16=casadi_sq(a00);
  a13=(a07+a16);
  a13=(a01*a13);
  a13=(a41-a13);
  a40=(a13*a06);
  a30=(a30-a40);
  a00=(a18*a00);
  a39=(a39*a14);
  a14=(a00-a39);
  a14=(a01*a14);
  a40=(a14*a26);
  a30=(a30+a40);
  a40=arg[1]? arg[1][4] : 0;
  a42=(a04*a40);
  a30=(a30-a42);
  if (res[0]!=0) res[0][14]=a30;
  a34=(a34*a20);
  a36=(a36*a31);
  a34=(a34-a36);
  a00=(a00+a39);
  a00=(a01*a00);
  a06=(a00*a06);
  a34=(a34-a06);
  a18=casadi_sq(a18);
  a07=(a07+a18);
  a07=(a01*a07);
  a07=(a41-a07);
  a26=(a07*a26);
  a34=(a34+a26);
  a26=arg[1]? arg[1][5] : 0;
  a04=(a04*a26);
  a34=(a34-a04);
  if (res[0]!=0) res[0][15]=a34;
  a34=(a23*a32);
  a04=(a15*a31);
  a34=(a34-a04);
  if (res[0]!=0) res[0][16]=a34;
  a34=(a15*a20);
  a32=(a02*a32);
  a34=(a34-a32);
  if (res[0]!=0) res[0][17]=a34;
  a31=(a02*a31);
  a20=(a23*a20);
  a31=(a31-a20);
  if (res[0]!=0) res[0][18]=a31;
  a31=arg[1]? arg[1][16] : 0;
  if (res[0]!=0) res[0][19]=a31;
  a31=arg[1]? arg[1][17] : 0;
  if (res[0]!=0) res[0][20]=a31;
  a31=arg[1]? arg[1][18] : 0;
  if (res[0]!=0) res[0][21]=a31;
  a31=arg[1]? arg[1][19] : 0;
  if (res[0]!=0) res[0][22]=a31;
  a31=arg[1]? arg[1][20] : 0;
  if (res[0]!=0) res[0][23]=a31;
  a31=arg[1]? arg[1][21] : 0;
  if (res[0]!=0) res[0][24]=a31;
  a31=(a29*a02);
  a20=(a14*a23);
  a31=(a31+a20);
  a20=(a07*a15);
  a31=(a31+a20);
  a31=(a03*a31);
  a31=(a31*a25);
  a20=(a33*a02);
  a34=(a13*a23);
  a20=(a20+a34);
  a34=(a00*a15);
  a20=(a20+a34);
  a03=(a03*a20);
  a03=(a03*a05);
  a31=(a31-a03);
  a15=(a15*a26);
  a31=(a31-a15);
  a23=(a23*a40);
  a31=(a31-a23);
  a02=(a02*a38);
  a31=(a31-a02);
  if (res[0]!=0) res[0][25]=a31;
  a31=arg[1]? arg[1][25] : 0;
  if (res[0]!=0) res[0][26]=a31;
  a31=arg[0]? arg[0][32] : 0;
  a02=arg[1]? arg[1][28] : 0;
  a23=(a31*a02);
  a15=arg[0]? arg[0][31] : 0;
  a03=arg[1]? arg[1][29] : 0;
  a20=(a15*a03);
  a23=(a23-a20);
  a20=(a33*a12);
  a23=(a23-a20);
  a18=(a18+a16);
  a18=(a01*a18);
  a41=(a41-a18);
  a18=(a41*a11);
  a23=(a23+a18);
  a18=(a29*a28);
  a23=(a23+a18);
  a18=(a10*a38);
  a23=(a23-a18);
  if (res[0]!=0) res[0][27]=a23;
  a23=arg[0]? arg[0][30] : 0;
  a18=(a23*a03);
  a16=arg[1]? arg[1][27] : 0;
  a31=(a31*a16);
  a18=(a18-a31);
  a31=(a13*a12);
  a18=(a18-a31);
  a37=(a37+a35);
  a37=(a01*a37);
  a35=(a37*a11);
  a18=(a18+a35);
  a35=(a14*a28);
  a18=(a18+a35);
  a35=(a10*a40);
  a18=(a18-a35);
  if (res[0]!=0) res[0][28]=a18;
  a15=(a15*a16);
  a23=(a23*a02);
  a15=(a15-a23);
  a12=(a00*a12);
  a15=(a15-a12);
  a27=(a27-a22);
  a01=(a01*a27);
  a11=(a01*a11);
  a15=(a15+a11);
  a28=(a07*a28);
  a15=(a15+a28);
  a10=(a10*a26);
  a15=(a15-a10);
  if (res[0]!=0) res[0][29]=a15;
  a15=(a21*a03);
  a10=(a17*a02);
  a15=(a15-a10);
  if (res[0]!=0) res[0][30]=a15;
  a15=(a17*a16);
  a03=(a08*a03);
  a15=(a15-a03);
  if (res[0]!=0) res[0][31]=a15;
  a02=(a08*a02);
  a16=(a21*a16);
  a02=(a02-a16);
  if (res[0]!=0) res[0][32]=a02;
  a02=arg[1]? arg[1][30] : 0;
  if (res[0]!=0) res[0][33]=a02;
  a02=arg[1]? arg[1][31] : 0;
  if (res[0]!=0) res[0][34]=a02;
  a02=arg[1]? arg[1][32] : 0;
  if (res[0]!=0) res[0][35]=a02;
  a02=arg[1]? arg[1][33] : 0;
  if (res[0]!=0) res[0][36]=a02;
  a02=arg[1]? arg[1][34] : 0;
  if (res[0]!=0) res[0][37]=a02;
  a02=arg[1]? arg[1][35] : 0;
  if (res[0]!=0) res[0][38]=a02;
  a41=(a41*a08);
  a37=(a37*a21);
  a41=(a41+a37);
  a01=(a01*a17);
  a41=(a41+a01);
  a41=(a19*a41);
  a33=(a33*a08);
  a13=(a13*a21);
  a33=(a33+a13);
  a00=(a00*a17);
  a33=(a33+a00);
  a33=(a09*a33);
  a41=(a41-a33);
  a41=(a41*a05);
  a29=(a29*a08);
  a14=(a14*a21);
  a29=(a29+a14);
  a07=(a07*a17);
  a29=(a29+a07);
  a09=(a09*a29);
  a09=(a09*a25);
  a41=(a41+a09);
  a19=(a19*a29);
  a19=(a19*a24);
  a41=(a41-a19);
  a17=(a17*a26);
  a41=(a41-a17);
  a21=(a21*a40);
  a41=(a41-a21);
  a08=(a08*a38);
  a41=(a41-a08);
  if (res[0]!=0) res[0][39]=a41;
  a41=arg[1]? arg[1][39] : 0;
  if (res[0]!=0) res[0][40]=a41;
  a41=arg[1]? arg[1][22] : 0;
  if (res[0]!=0) res[0][41]=a41;
  a41=arg[1]? arg[1][23] : 0;
  if (res[0]!=0) res[0][42]=a41;
  a41=arg[1]? arg[1][24] : 0;
  if (res[0]!=0) res[0][43]=a41;
  a41=arg[1]? arg[1][26] : 0;
  if (res[0]!=0) res[0][44]=a41;
  a41=arg[1]? arg[1][36] : 0;
  if (res[0]!=0) res[0][45]=a41;
  a41=arg[1]? arg[1][37] : 0;
  if (res[0]!=0) res[0][46]=a41;
  a41=arg[1]? arg[1][38] : 0;
  if (res[0]!=0) res[0][47]=a41;
  a41=arg[1]? arg[1][40] : 0;
  if (res[0]!=0) res[0][48]=a41;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_2cables_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_2cables_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_2cables_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinodynamic_load_2cables_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_2cables_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinodynamic_load_2cables_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void kinodynamic_load_2cables_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void kinodynamic_load_2cables_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int kinodynamic_load_2cables_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int kinodynamic_load_2cables_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real kinodynamic_load_2cables_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinodynamic_load_2cables_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinodynamic_load_2cables_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinodynamic_load_2cables_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinodynamic_load_2cables_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_2cables_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_2cables_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
