/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) kinodynamic_load_3cables_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {55, 1, 1};
static const casadi_int casadi_s1[3] = {12, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {67, 1, 1};

/* kinodynamic_load_3cables_expl_vde_adj:(i0[55],i1[55],i2[12],i3[0])->(o0[67]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[0]? arg[0][9] : 0;
  a01=2.;
  a02=arg[0]? arg[0][41] : 0;
  a03=-1.5000000000000013e-01;
  a04=arg[0]? arg[0][53] : 0;
  a05=2.3076923076923077e+01;
  a06=arg[1]? arg[1][12] : 0;
  a05=(a05*a06);
  a06=(a04*a05);
  a07=(a03*a06);
  a08=(a02*a07);
  a09=arg[0]? arg[0][13] : 0;
  a10=2.9999999999999999e-01;
  a11=arg[0]? arg[0][25] : 0;
  a12=(a11*a05);
  a12=(a10*a12);
  a13=(a09*a12);
  a08=(a08+a13);
  a13=arg[0]? arg[0][27] : 0;
  a14=-1.4999999999999994e-01;
  a15=arg[0]? arg[0][39] : 0;
  a16=(a15*a05);
  a17=(a14*a16);
  a18=(a13*a17);
  a08=(a08+a18);
  a08=(a01*a08);
  a18=(a00*a08);
  a19=arg[0]? arg[0][7] : 0;
  a20=arg[0]? arg[0][43] : 0;
  a21=(a20*a07);
  a22=arg[0]? arg[0][15] : 0;
  a23=(a22*a12);
  a21=(a21+a23);
  a23=arg[0]? arg[0][29] : 0;
  a24=(a23*a17);
  a21=(a21+a24);
  a21=(a01*a21);
  a24=(a19*a21);
  a18=(a18-a24);
  a24=arg[0]? arg[0][8] : 0;
  a25=-2.5980762113533151e-01;
  a06=(a25*a06);
  a26=(a20*a06);
  a27=2.5980762113533162e-01;
  a16=(a27*a16);
  a28=(a23*a16);
  a26=(a26+a28);
  a26=(a01*a26);
  a28=(a24*a26);
  a18=(a18-a28);
  a28=arg[0]? arg[0][42] : 0;
  a29=(a28*a06);
  a30=arg[0]? arg[0][28] : 0;
  a31=(a30*a16);
  a29=(a29+a31);
  a29=(a01*a29);
  a31=(a00*a29);
  a18=(a18+a31);
  a31=arg[0]? arg[0][14] : 0;
  a32=30.;
  a33=arg[1]? arg[1][11] : 0;
  a32=(a32*a33);
  a33=(a11*a32);
  a33=(a10*a33);
  a34=(a31*a33);
  a35=(a04*a32);
  a35=(a03*a35);
  a36=5.9999999999999986e+01;
  a37=arg[1]? arg[1][10] : 0;
  a36=(a36*a37);
  a37=(a04*a36);
  a37=(a25*a37);
  a35=(a35-a37);
  a37=(a28*a35);
  a34=(a34+a37);
  a37=(a15*a32);
  a37=(a14*a37);
  a38=(a15*a36);
  a38=(a27*a38);
  a37=(a37-a38);
  a38=(a30*a37);
  a34=(a34+a38);
  a34=(a01*a34);
  a38=(a19*a34);
  a18=(a18-a38);
  a38=(a09*a33);
  a39=(a02*a35);
  a38=(a38+a39);
  a39=(a13*a37);
  a38=(a38+a39);
  a38=(a01*a38);
  a39=(a24*a38);
  a18=(a18+a39);
  a39=arg[0]? arg[0][12] : 0;
  a40=5.0000000000000000e-01;
  a41=arg[1]? arg[1][9] : 0;
  a41=(a40*a41);
  a42=(a39*a41);
  a18=(a18+a42);
  a42=arg[0]? arg[0][11] : 0;
  a43=arg[1]? arg[1][8] : 0;
  a43=(a40*a43);
  a44=(a42*a43);
  a18=(a18+a44);
  a44=arg[0]? arg[0][10] : 0;
  a45=arg[1]? arg[1][7] : 0;
  a45=(a40*a45);
  a46=(a44*a45);
  a18=(a18+a46);
  if (res[0]!=0) res[0][6]=a18;
  a18=(a19+a19);
  a46=(a28*a07);
  a47=(a31*a12);
  a46=(a46+a47);
  a47=(a30*a17);
  a46=(a46+a47);
  a46=(a01*a46);
  a47=(a18*a46);
  a48=arg[0]? arg[0][6] : 0;
  a49=(a48*a21);
  a47=(a47-a49);
  a49=(a24*a08);
  a47=(a47-a49);
  a49=(a00*a26);
  a47=(a47+a49);
  a49=(a24*a29);
  a47=(a47+a49);
  a49=(a22*a33);
  a50=(a20*a35);
  a49=(a49+a50);
  a50=(a23*a37);
  a49=(a49+a50);
  a49=(a01*a49);
  a18=(a18*a49);
  a47=(a47-a18);
  a18=(a48*a34);
  a47=(a47-a18);
  a18=(a00*a38);
  a47=(a47+a18);
  a18=(a42*a41);
  a47=(a47+a18);
  a18=(a39*a43);
  a47=(a47-a18);
  a18=arg[1]? arg[1][6] : 0;
  a40=(a40*a18);
  a18=(a44*a40);
  a47=(a47-a18);
  if (res[0]!=0) res[0][7]=a47;
  a47=(a19*a29);
  a18=(a00*a21);
  a50=(a19*a08);
  a18=(a18+a50);
  a50=(a48*a26);
  a18=(a18+a50);
  a47=(a47-a18);
  a18=(a24+a24);
  a50=(a02*a06);
  a51=(a13*a16);
  a50=(a50+a51);
  a50=(a01*a50);
  a51=(a18*a50);
  a47=(a47-a51);
  a18=(a18*a49);
  a47=(a47-a18);
  a18=(a00*a34);
  a47=(a47+a18);
  a18=(a48*a38);
  a47=(a47+a18);
  a18=(a44*a41);
  a47=(a47-a18);
  a18=(a39*a45);
  a47=(a47+a18);
  a18=(a42*a40);
  a47=(a47-a18);
  if (res[0]!=0) res[0][8]=a47;
  a47=(a00+a00);
  a46=(a47*a46);
  a21=(a24*a21);
  a46=(a46-a21);
  a08=(a48*a08);
  a46=(a46+a08);
  a26=(a19*a26);
  a46=(a46+a26);
  a29=(a48*a29);
  a46=(a46+a29);
  a47=(a47*a50);
  a46=(a46-a47);
  a34=(a24*a34);
  a46=(a46+a34);
  a38=(a19*a38);
  a46=(a46+a38);
  a38=(a44*a43);
  a46=(a46+a38);
  a38=(a42*a45);
  a46=(a46-a38);
  a38=(a39*a40);
  a46=(a46-a38);
  if (res[0]!=0) res[0][9]=a46;
  a46=4.3333333333333335e-02;
  a38=(a46*a39);
  a34=(a38*a32);
  a47=3.3333333333333333e-02;
  a50=(a47*a42);
  a29=(a50*a05);
  a34=(a34-a29);
  a29=1.6666666666666670e-02;
  a26=(a42*a05);
  a08=(a39*a32);
  a26=(a26-a08);
  a26=(a29*a26);
  a34=(a34+a26);
  a26=(a24*a41);
  a34=(a34-a26);
  a26=(a00*a43);
  a34=(a34+a26);
  a26=(a48*a45);
  a34=(a34+a26);
  a26=(a19*a40);
  a34=(a34-a26);
  if (res[0]!=0) res[0][10]=a34;
  a29=(a29*a44);
  a34=(a29*a05);
  a39=(a39*a36);
  a26=(a44*a05);
  a39=(a39-a26);
  a47=(a47*a39);
  a34=(a34+a47);
  a38=(a38*a36);
  a34=(a34-a38);
  a38=(a19*a41);
  a34=(a34+a38);
  a38=(a48*a43);
  a34=(a34+a38);
  a38=(a00*a45);
  a34=(a34-a38);
  a38=(a24*a40);
  a34=(a34-a38);
  if (res[0]!=0) res[0][11]=a34;
  a50=(a50*a36);
  a29=(a29*a32);
  a50=(a50-a29);
  a44=(a44*a32);
  a42=(a42*a36);
  a44=(a44-a42);
  a46=(a46*a44);
  a50=(a50+a46);
  a41=(a48*a41);
  a50=(a50+a41);
  a43=(a19*a43);
  a50=(a50-a43);
  a45=(a24*a45);
  a50=(a50+a45);
  a40=(a00*a40);
  a50=(a50-a40);
  if (res[0]!=0) res[0][12]=a50;
  a50=arg[0]? arg[0][18] : 0;
  a40=arg[1]? arg[1][14] : 0;
  a45=(a50*a40);
  a43=arg[0]? arg[0][17] : 0;
  a41=arg[1]? arg[1][15] : 0;
  a46=(a43*a41);
  a45=(a45-a46);
  a46=(a19*a24);
  a44=(a48*a00);
  a42=(a46-a44);
  a42=(a01*a42);
  a29=(a42*a12);
  a45=(a45-a29);
  a29=(a19*a00);
  a34=(a48*a24);
  a38=(a29+a34);
  a38=(a01*a38);
  a47=(a38*a33);
  a45=(a45+a47);
  a47=arg[1]? arg[1][3] : 0;
  a39=(a11*a47);
  a45=(a45-a39);
  if (res[0]!=0) res[0][13]=a45;
  a45=arg[0]? arg[0][16] : 0;
  a39=(a45*a41);
  a26=arg[1]? arg[1][13] : 0;
  a50=(a50*a26);
  a39=(a39-a50);
  a50=1.;
  a08=casadi_sq(a19);
  a21=casadi_sq(a00);
  a18=(a08+a21);
  a18=(a01*a18);
  a18=(a50-a18);
  a49=(a18*a12);
  a39=(a39-a49);
  a00=(a24*a00);
  a48=(a48*a19);
  a19=(a00-a48);
  a19=(a01*a19);
  a49=(a19*a33);
  a39=(a39+a49);
  a49=arg[1]? arg[1][4] : 0;
  a51=(a11*a49);
  a39=(a39-a51);
  if (res[0]!=0) res[0][14]=a39;
  a43=(a43*a26);
  a45=(a45*a40);
  a43=(a43-a45);
  a00=(a00+a48);
  a00=(a01*a00);
  a12=(a00*a12);
  a43=(a43-a12);
  a24=casadi_sq(a24);
  a08=(a08+a24);
  a08=(a01*a08);
  a08=(a50-a08);
  a33=(a08*a33);
  a43=(a43+a33);
  a33=arg[1]? arg[1][5] : 0;
  a11=(a11*a33);
  a43=(a43-a11);
  if (res[0]!=0) res[0][15]=a43;
  a43=(a31*a41);
  a11=(a22*a40);
  a43=(a43-a11);
  if (res[0]!=0) res[0][16]=a43;
  a43=(a22*a26);
  a41=(a09*a41);
  a43=(a43-a41);
  if (res[0]!=0) res[0][17]=a43;
  a40=(a09*a40);
  a26=(a31*a26);
  a40=(a40-a26);
  if (res[0]!=0) res[0][18]=a40;
  a40=arg[1]? arg[1][16] : 0;
  if (res[0]!=0) res[0][19]=a40;
  a40=arg[1]? arg[1][17] : 0;
  if (res[0]!=0) res[0][20]=a40;
  a40=arg[1]? arg[1][18] : 0;
  if (res[0]!=0) res[0][21]=a40;
  a40=arg[1]? arg[1][19] : 0;
  if (res[0]!=0) res[0][22]=a40;
  a40=arg[1]? arg[1][20] : 0;
  if (res[0]!=0) res[0][23]=a40;
  a40=arg[1]? arg[1][21] : 0;
  if (res[0]!=0) res[0][24]=a40;
  a40=(a38*a09);
  a26=(a19*a31);
  a40=(a40+a26);
  a26=(a08*a22);
  a40=(a40+a26);
  a40=(a10*a40);
  a40=(a40*a32);
  a26=(a42*a09);
  a43=(a18*a31);
  a26=(a26+a43);
  a43=(a00*a22);
  a26=(a26+a43);
  a10=(a10*a26);
  a10=(a10*a05);
  a40=(a40-a10);
  a22=(a22*a33);
  a40=(a40-a22);
  a31=(a31*a49);
  a40=(a40-a31);
  a09=(a09*a47);
  a40=(a40-a09);
  if (res[0]!=0) res[0][25]=a40;
  a40=arg[1]? arg[1][25] : 0;
  if (res[0]!=0) res[0][26]=a40;
  a40=arg[0]? arg[0][32] : 0;
  a09=arg[1]? arg[1][28] : 0;
  a31=(a40*a09);
  a22=arg[0]? arg[0][31] : 0;
  a10=arg[1]? arg[1][29] : 0;
  a26=(a22*a10);
  a31=(a31-a26);
  a26=(a42*a17);
  a31=(a31-a26);
  a24=(a24+a21);
  a24=(a01*a24);
  a50=(a50-a24);
  a24=(a50*a16);
  a31=(a31+a24);
  a24=(a38*a37);
  a31=(a31+a24);
  a24=(a15*a47);
  a31=(a31-a24);
  if (res[0]!=0) res[0][27]=a31;
  a31=arg[0]? arg[0][30] : 0;
  a24=(a31*a10);
  a21=arg[1]? arg[1][27] : 0;
  a40=(a40*a21);
  a24=(a24-a40);
  a40=(a18*a17);
  a24=(a24-a40);
  a46=(a46+a44);
  a46=(a01*a46);
  a44=(a46*a16);
  a24=(a24+a44);
  a44=(a19*a37);
  a24=(a24+a44);
  a44=(a15*a49);
  a24=(a24-a44);
  if (res[0]!=0) res[0][28]=a24;
  a22=(a22*a21);
  a31=(a31*a09);
  a22=(a22-a31);
  a17=(a00*a17);
  a22=(a22-a17);
  a29=(a29-a34);
  a01=(a01*a29);
  a16=(a01*a16);
  a22=(a22+a16);
  a37=(a08*a37);
  a22=(a22+a37);
  a15=(a15*a33);
  a22=(a22-a15);
  if (res[0]!=0) res[0][29]=a22;
  a22=(a30*a10);
  a15=(a23*a09);
  a22=(a22-a15);
  if (res[0]!=0) res[0][30]=a22;
  a22=(a23*a21);
  a10=(a13*a10);
  a22=(a22-a10);
  if (res[0]!=0) res[0][31]=a22;
  a09=(a13*a09);
  a21=(a30*a21);
  a09=(a09-a21);
  if (res[0]!=0) res[0][32]=a09;
  a09=arg[1]? arg[1][30] : 0;
  if (res[0]!=0) res[0][33]=a09;
  a09=arg[1]? arg[1][31] : 0;
  if (res[0]!=0) res[0][34]=a09;
  a09=arg[1]? arg[1][32] : 0;
  if (res[0]!=0) res[0][35]=a09;
  a09=arg[1]? arg[1][33] : 0;
  if (res[0]!=0) res[0][36]=a09;
  a09=arg[1]? arg[1][34] : 0;
  if (res[0]!=0) res[0][37]=a09;
  a09=arg[1]? arg[1][35] : 0;
  if (res[0]!=0) res[0][38]=a09;
  a09=(a50*a13);
  a21=(a46*a30);
  a09=(a09+a21);
  a21=(a01*a23);
  a09=(a09+a21);
  a09=(a27*a09);
  a21=(a42*a13);
  a22=(a18*a30);
  a21=(a21+a22);
  a22=(a00*a23);
  a21=(a21+a22);
  a21=(a14*a21);
  a09=(a09-a21);
  a09=(a09*a05);
  a21=(a38*a13);
  a22=(a19*a30);
  a21=(a21+a22);
  a22=(a08*a23);
  a21=(a21+a22);
  a14=(a14*a21);
  a14=(a14*a32);
  a09=(a09+a14);
  a27=(a27*a21);
  a27=(a27*a36);
  a09=(a09-a27);
  a23=(a23*a33);
  a09=(a09-a23);
  a30=(a30*a49);
  a09=(a09-a30);
  a13=(a13*a47);
  a09=(a09-a13);
  if (res[0]!=0) res[0][39]=a09;
  a09=arg[1]? arg[1][39] : 0;
  if (res[0]!=0) res[0][40]=a09;
  a09=arg[0]? arg[0][46] : 0;
  a13=arg[1]? arg[1][42] : 0;
  a30=(a09*a13);
  a23=arg[0]? arg[0][45] : 0;
  a27=arg[1]? arg[1][43] : 0;
  a21=(a23*a27);
  a30=(a30-a21);
  a21=(a42*a07);
  a30=(a30-a21);
  a21=(a50*a06);
  a30=(a30+a21);
  a21=(a38*a35);
  a30=(a30+a21);
  a21=(a04*a47);
  a30=(a30-a21);
  if (res[0]!=0) res[0][41]=a30;
  a30=arg[0]? arg[0][44] : 0;
  a21=(a30*a27);
  a14=arg[1]? arg[1][41] : 0;
  a09=(a09*a14);
  a21=(a21-a09);
  a09=(a18*a07);
  a21=(a21-a09);
  a09=(a46*a06);
  a21=(a21+a09);
  a09=(a19*a35);
  a21=(a21+a09);
  a09=(a04*a49);
  a21=(a21-a09);
  if (res[0]!=0) res[0][42]=a21;
  a23=(a23*a14);
  a30=(a30*a13);
  a23=(a23-a30);
  a07=(a00*a07);
  a23=(a23-a07);
  a06=(a01*a06);
  a23=(a23+a06);
  a35=(a08*a35);
  a23=(a23+a35);
  a04=(a04*a33);
  a23=(a23-a04);
  if (res[0]!=0) res[0][43]=a23;
  a23=(a28*a27);
  a04=(a20*a13);
  a23=(a23-a04);
  if (res[0]!=0) res[0][44]=a23;
  a23=(a20*a14);
  a27=(a02*a27);
  a23=(a23-a27);
  if (res[0]!=0) res[0][45]=a23;
  a13=(a02*a13);
  a14=(a28*a14);
  a13=(a13-a14);
  if (res[0]!=0) res[0][46]=a13;
  a13=arg[1]? arg[1][44] : 0;
  if (res[0]!=0) res[0][47]=a13;
  a13=arg[1]? arg[1][45] : 0;
  if (res[0]!=0) res[0][48]=a13;
  a13=arg[1]? arg[1][46] : 0;
  if (res[0]!=0) res[0][49]=a13;
  a13=arg[1]? arg[1][47] : 0;
  if (res[0]!=0) res[0][50]=a13;
  a13=arg[1]? arg[1][48] : 0;
  if (res[0]!=0) res[0][51]=a13;
  a13=arg[1]? arg[1][49] : 0;
  if (res[0]!=0) res[0][52]=a13;
  a50=(a50*a02);
  a46=(a46*a28);
  a50=(a50+a46);
  a01=(a01*a20);
  a50=(a50+a01);
  a50=(a25*a50);
  a42=(a42*a02);
  a18=(a18*a28);
  a42=(a42+a18);
  a00=(a00*a20);
  a42=(a42+a00);
  a42=(a03*a42);
  a50=(a50-a42);
  a50=(a50*a05);
  a38=(a38*a02);
  a19=(a19*a28);
  a38=(a38+a19);
  a08=(a08*a20);
  a38=(a38+a08);
  a03=(a03*a38);
  a03=(a03*a32);
  a50=(a50+a03);
  a25=(a25*a38);
  a25=(a25*a36);
  a50=(a50-a25);
  a20=(a20*a33);
  a50=(a50-a20);
  a28=(a28*a49);
  a50=(a50-a28);
  a02=(a02*a47);
  a50=(a50-a02);
  if (res[0]!=0) res[0][53]=a50;
  a50=arg[1]? arg[1][53] : 0;
  if (res[0]!=0) res[0][54]=a50;
  a50=arg[1]? arg[1][22] : 0;
  if (res[0]!=0) res[0][55]=a50;
  a50=arg[1]? arg[1][23] : 0;
  if (res[0]!=0) res[0][56]=a50;
  a50=arg[1]? arg[1][24] : 0;
  if (res[0]!=0) res[0][57]=a50;
  a50=arg[1]? arg[1][26] : 0;
  if (res[0]!=0) res[0][58]=a50;
  a50=arg[1]? arg[1][36] : 0;
  if (res[0]!=0) res[0][59]=a50;
  a50=arg[1]? arg[1][37] : 0;
  if (res[0]!=0) res[0][60]=a50;
  a50=arg[1]? arg[1][38] : 0;
  if (res[0]!=0) res[0][61]=a50;
  a50=arg[1]? arg[1][40] : 0;
  if (res[0]!=0) res[0][62]=a50;
  a50=arg[1]? arg[1][50] : 0;
  if (res[0]!=0) res[0][63]=a50;
  a50=arg[1]? arg[1][51] : 0;
  if (res[0]!=0) res[0][64]=a50;
  a50=arg[1]? arg[1][52] : 0;
  if (res[0]!=0) res[0][65]=a50;
  a50=arg[1]? arg[1][54] : 0;
  if (res[0]!=0) res[0][66]=a50;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_3cables_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_3cables_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_3cables_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinodynamic_load_3cables_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_3cables_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinodynamic_load_3cables_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void kinodynamic_load_3cables_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void kinodynamic_load_3cables_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int kinodynamic_load_3cables_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int kinodynamic_load_3cables_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real kinodynamic_load_3cables_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinodynamic_load_3cables_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinodynamic_load_3cables_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinodynamic_load_3cables_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinodynamic_load_3cables_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_3cables_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_3cables_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
