/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) kinodynamic_load_3cables_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {55, 1, 1};
static const casadi_int casadi_s1[3] = {12, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};

/* kinodynamic_load_3cables_expl_ode_fun:(i0[55],i1[12],i2[0])->(o0[55]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39;
  a00=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[0]? arg[0][25] : 0;
  a01=arg[0]? arg[0][13] : 0;
  a02=(a00*a01);
  a03=arg[0]? arg[0][39] : 0;
  a04=arg[0]? arg[0][27] : 0;
  a05=(a03*a04);
  a02=(a02+a05);
  a05=arg[0]? arg[0][53] : 0;
  a06=arg[0]? arg[0][41] : 0;
  a07=(a05*a06);
  a02=(a02+a07);
  a02=(-a02);
  if (res[0]!=0) res[0][3]=a02;
  a02=arg[0]? arg[0][14] : 0;
  a07=(a00*a02);
  a08=arg[0]? arg[0][28] : 0;
  a09=(a03*a08);
  a07=(a07+a09);
  a09=arg[0]? arg[0][42] : 0;
  a10=(a05*a09);
  a07=(a07+a10);
  a07=(-a07);
  if (res[0]!=0) res[0][4]=a07;
  a07=-9.8100000000000005e+00;
  a10=arg[0]? arg[0][15] : 0;
  a11=(a00*a10);
  a12=arg[0]? arg[0][29] : 0;
  a13=(a03*a12);
  a11=(a11+a13);
  a13=arg[0]? arg[0][43] : 0;
  a14=(a05*a13);
  a11=(a11+a14);
  a07=(a07-a11);
  if (res[0]!=0) res[0][5]=a07;
  a07=5.0000000000000000e-01;
  a11=arg[0]? arg[0][7] : 0;
  a14=arg[0]? arg[0][10] : 0;
  a15=(a11*a14);
  a16=arg[0]? arg[0][8] : 0;
  a17=arg[0]? arg[0][11] : 0;
  a18=(a16*a17);
  a15=(a15+a18);
  a18=arg[0]? arg[0][9] : 0;
  a19=arg[0]? arg[0][12] : 0;
  a20=(a18*a19);
  a15=(a15+a20);
  a15=(a07*a15);
  a15=(-a15);
  if (res[0]!=0) res[0][6]=a15;
  a15=arg[0]? arg[0][6] : 0;
  a20=(a15*a14);
  a21=(a18*a17);
  a20=(a20-a21);
  a21=(a16*a19);
  a20=(a20+a21);
  a20=(a07*a20);
  if (res[0]!=0) res[0][7]=a20;
  a20=(a18*a14);
  a21=(a15*a17);
  a20=(a20+a21);
  a21=(a11*a19);
  a20=(a20-a21);
  a20=(a07*a20);
  if (res[0]!=0) res[0][8]=a20;
  a20=(a11*a17);
  a21=(a16*a14);
  a20=(a20-a21);
  a21=(a15*a19);
  a20=(a20+a21);
  a07=(a07*a20);
  if (res[0]!=0) res[0][9]=a07;
  a07=5.9999999999999986e+01;
  a20=4.3333333333333335e-02;
  a20=(a20*a19);
  a21=(a17*a20);
  a22=3.3333333333333333e-02;
  a22=(a22*a17);
  a23=(a19*a22);
  a21=(a21-a23);
  a23=2.5980762113533162e-01;
  a24=2.;
  a25=(a11*a18);
  a26=(a15*a16);
  a27=(a25+a26);
  a27=(a24*a27);
  a28=(a27*a04);
  a29=(a16*a18);
  a30=(a15*a11);
  a31=(a29-a30);
  a31=(a24*a31);
  a32=(a31*a08);
  a28=(a28+a32);
  a32=1.;
  a33=casadi_sq(a11);
  a34=casadi_sq(a16);
  a35=(a33+a34);
  a35=(a24*a35);
  a35=(a32-a35);
  a36=(a35*a12);
  a28=(a28+a36);
  a36=(a23*a28);
  a36=(a03*a36);
  a37=-2.5980762113533151e-01;
  a38=(a27*a06);
  a39=(a31*a09);
  a38=(a38+a39);
  a39=(a35*a13);
  a38=(a38+a39);
  a39=(a37*a38);
  a39=(a05*a39);
  a36=(a36+a39);
  a21=(a21+a36);
  a07=(a07*a21);
  a07=(-a07);
  if (res[0]!=0) res[0][10]=a07;
  a07=30.;
  a21=2.9999999999999999e-01;
  a27=(a27*a01);
  a31=(a31*a02);
  a27=(a27+a31);
  a35=(a35*a10);
  a27=(a27+a35);
  a27=(a21*a27);
  a27=(a00*a27);
  a35=-1.4999999999999994e-01;
  a28=(a35*a28);
  a28=(a03*a28);
  a27=(a27+a28);
  a28=-1.5000000000000013e-01;
  a38=(a28*a38);
  a38=(a05*a38);
  a27=(a27+a38);
  a38=1.6666666666666670e-02;
  a38=(a38*a14);
  a19=(a19*a38);
  a20=(a14*a20);
  a19=(a19-a20);
  a27=(a27-a19);
  a07=(a07*a27);
  if (res[0]!=0) res[0][11]=a07;
  a07=2.3076923076923077e+01;
  a27=casadi_sq(a18);
  a34=(a34+a27);
  a34=(a24*a34);
  a34=(a32-a34);
  a19=(a34*a04);
  a11=(a11*a16);
  a15=(a15*a18);
  a18=(a11+a15);
  a18=(a24*a18);
  a16=(a18*a08);
  a19=(a19+a16);
  a25=(a25-a26);
  a25=(a24*a25);
  a26=(a25*a12);
  a19=(a19+a26);
  a23=(a23*a19);
  a11=(a11-a15);
  a11=(a24*a11);
  a15=(a11*a04);
  a33=(a33+a27);
  a33=(a24*a33);
  a32=(a32-a33);
  a33=(a32*a08);
  a15=(a15+a33);
  a29=(a29+a30);
  a24=(a24*a29);
  a29=(a24*a12);
  a15=(a15+a29);
  a35=(a35*a15);
  a23=(a23-a35);
  a03=(a03*a23);
  a23=(a11*a01);
  a35=(a32*a02);
  a23=(a23+a35);
  a35=(a24*a10);
  a23=(a23+a35);
  a21=(a21*a23);
  a00=(a00*a21);
  a03=(a03-a00);
  a34=(a34*a06);
  a18=(a18*a09);
  a34=(a34+a18);
  a25=(a25*a13);
  a34=(a34+a25);
  a37=(a37*a34);
  a11=(a11*a06);
  a32=(a32*a09);
  a11=(a11+a32);
  a24=(a24*a13);
  a11=(a11+a24);
  a28=(a28*a11);
  a37=(a37-a28);
  a05=(a05*a37);
  a03=(a03+a05);
  a14=(a14*a22);
  a17=(a17*a38);
  a14=(a14-a17);
  a03=(a03-a14);
  a07=(a07*a03);
  if (res[0]!=0) res[0][12]=a07;
  a07=arg[0]? arg[0][17] : 0;
  a03=(a07*a10);
  a14=arg[0]? arg[0][18] : 0;
  a17=(a14*a02);
  a03=(a03-a17);
  if (res[0]!=0) res[0][13]=a03;
  a14=(a14*a01);
  a03=arg[0]? arg[0][16] : 0;
  a10=(a03*a10);
  a14=(a14-a10);
  if (res[0]!=0) res[0][14]=a14;
  a03=(a03*a02);
  a07=(a07*a01);
  a03=(a03-a07);
  if (res[0]!=0) res[0][15]=a03;
  a03=arg[0]? arg[0][19] : 0;
  if (res[0]!=0) res[0][16]=a03;
  a03=arg[0]? arg[0][20] : 0;
  if (res[0]!=0) res[0][17]=a03;
  a03=arg[0]? arg[0][21] : 0;
  if (res[0]!=0) res[0][18]=a03;
  a03=arg[0]? arg[0][22] : 0;
  if (res[0]!=0) res[0][19]=a03;
  a03=arg[0]? arg[0][23] : 0;
  if (res[0]!=0) res[0][20]=a03;
  a03=arg[0]? arg[0][24] : 0;
  if (res[0]!=0) res[0][21]=a03;
  a03=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][22]=a03;
  a03=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][23]=a03;
  a03=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][24]=a03;
  a03=arg[0]? arg[0][26] : 0;
  if (res[0]!=0) res[0][25]=a03;
  a03=arg[1]? arg[1][3] : 0;
  if (res[0]!=0) res[0][26]=a03;
  a03=arg[0]? arg[0][31] : 0;
  a07=(a03*a12);
  a01=arg[0]? arg[0][32] : 0;
  a02=(a01*a08);
  a07=(a07-a02);
  if (res[0]!=0) res[0][27]=a07;
  a01=(a01*a04);
  a07=arg[0]? arg[0][30] : 0;
  a12=(a07*a12);
  a01=(a01-a12);
  if (res[0]!=0) res[0][28]=a01;
  a07=(a07*a08);
  a03=(a03*a04);
  a07=(a07-a03);
  if (res[0]!=0) res[0][29]=a07;
  a07=arg[0]? arg[0][33] : 0;
  if (res[0]!=0) res[0][30]=a07;
  a07=arg[0]? arg[0][34] : 0;
  if (res[0]!=0) res[0][31]=a07;
  a07=arg[0]? arg[0][35] : 0;
  if (res[0]!=0) res[0][32]=a07;
  a07=arg[0]? arg[0][36] : 0;
  if (res[0]!=0) res[0][33]=a07;
  a07=arg[0]? arg[0][37] : 0;
  if (res[0]!=0) res[0][34]=a07;
  a07=arg[0]? arg[0][38] : 0;
  if (res[0]!=0) res[0][35]=a07;
  a07=arg[1]? arg[1][4] : 0;
  if (res[0]!=0) res[0][36]=a07;
  a07=arg[1]? arg[1][5] : 0;
  if (res[0]!=0) res[0][37]=a07;
  a07=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][38]=a07;
  a07=arg[0]? arg[0][40] : 0;
  if (res[0]!=0) res[0][39]=a07;
  a07=arg[1]? arg[1][7] : 0;
  if (res[0]!=0) res[0][40]=a07;
  a07=arg[0]? arg[0][45] : 0;
  a03=(a07*a13);
  a04=arg[0]? arg[0][46] : 0;
  a08=(a04*a09);
  a03=(a03-a08);
  if (res[0]!=0) res[0][41]=a03;
  a04=(a04*a06);
  a03=arg[0]? arg[0][44] : 0;
  a13=(a03*a13);
  a04=(a04-a13);
  if (res[0]!=0) res[0][42]=a04;
  a03=(a03*a09);
  a07=(a07*a06);
  a03=(a03-a07);
  if (res[0]!=0) res[0][43]=a03;
  a03=arg[0]? arg[0][47] : 0;
  if (res[0]!=0) res[0][44]=a03;
  a03=arg[0]? arg[0][48] : 0;
  if (res[0]!=0) res[0][45]=a03;
  a03=arg[0]? arg[0][49] : 0;
  if (res[0]!=0) res[0][46]=a03;
  a03=arg[0]? arg[0][50] : 0;
  if (res[0]!=0) res[0][47]=a03;
  a03=arg[0]? arg[0][51] : 0;
  if (res[0]!=0) res[0][48]=a03;
  a03=arg[0]? arg[0][52] : 0;
  if (res[0]!=0) res[0][49]=a03;
  a03=arg[1]? arg[1][8] : 0;
  if (res[0]!=0) res[0][50]=a03;
  a03=arg[1]? arg[1][9] : 0;
  if (res[0]!=0) res[0][51]=a03;
  a03=arg[1]? arg[1][10] : 0;
  if (res[0]!=0) res[0][52]=a03;
  a03=arg[0]? arg[0][54] : 0;
  if (res[0]!=0) res[0][53]=a03;
  a03=arg[1]? arg[1][11] : 0;
  if (res[0]!=0) res[0][54]=a03;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_3cables_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_3cables_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_3cables_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinodynamic_load_3cables_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_3cables_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinodynamic_load_3cables_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void kinodynamic_load_3cables_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void kinodynamic_load_3cables_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int kinodynamic_load_3cables_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int kinodynamic_load_3cables_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real kinodynamic_load_3cables_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinodynamic_load_3cables_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinodynamic_load_3cables_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinodynamic_load_3cables_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinodynamic_load_3cables_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_3cables_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_3cables_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
