/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) distributed_single_cable_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {27, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {9, 1, 1};

/* distributed_single_cable_expl_ode_fun:(i0[27],i1[4],i2[9])->(o0[27]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24;
  a00=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[0]? arg[0][25] : 0;
  a01=arg[0]? arg[0][13] : 0;
  a02=(a00*a01);
  a03=arg[2]? arg[2][0] : 0;
  a02=(a02+a03);
  a02=(-a02);
  if (res[0]!=0) res[0][3]=a02;
  a02=arg[0]? arg[0][14] : 0;
  a03=(a00*a02);
  a04=arg[2]? arg[2][1] : 0;
  a03=(a03+a04);
  a03=(-a03);
  if (res[0]!=0) res[0][4]=a03;
  a03=-9.8100000000000005e+00;
  a04=arg[0]? arg[0][15] : 0;
  a05=(a00*a04);
  a06=arg[2]? arg[2][2] : 0;
  a05=(a05+a06);
  a03=(a03-a05);
  if (res[0]!=0) res[0][5]=a03;
  a03=5.0000000000000000e-01;
  a05=arg[0]? arg[0][7] : 0;
  a06=arg[0]? arg[0][10] : 0;
  a07=(a05*a06);
  a08=arg[0]? arg[0][8] : 0;
  a09=arg[0]? arg[0][11] : 0;
  a10=(a08*a09);
  a07=(a07+a10);
  a10=arg[0]? arg[0][9] : 0;
  a11=arg[0]? arg[0][12] : 0;
  a12=(a10*a11);
  a07=(a07+a12);
  a07=(a03*a07);
  a07=(-a07);
  if (res[0]!=0) res[0][6]=a07;
  a07=arg[0]? arg[0][6] : 0;
  a12=(a07*a06);
  a13=(a08*a11);
  a12=(a12+a13);
  a13=(a10*a09);
  a12=(a12-a13);
  a12=(a03*a12);
  if (res[0]!=0) res[0][7]=a12;
  a12=(a07*a09);
  a13=(a10*a06);
  a12=(a12+a13);
  a13=(a05*a11);
  a12=(a12-a13);
  a12=(a03*a12);
  if (res[0]!=0) res[0][8]=a12;
  a12=(a07*a11);
  a13=(a05*a09);
  a12=(a12+a13);
  a13=(a08*a06);
  a12=(a12-a13);
  a03=(a03*a12);
  if (res[0]!=0) res[0][9]=a03;
  a03=5.9999999999999986e+01;
  a12=2.;
  a13=(a05*a08);
  a14=(a07*a10);
  a15=(a13-a14);
  a15=(a12*a15);
  a15=(a15*a01);
  a16=1.;
  a17=casadi_sq(a05);
  a18=casadi_sq(a10);
  a19=(a17+a18);
  a19=(a12*a19);
  a19=(a16-a19);
  a19=(a19*a02);
  a15=(a15+a19);
  a19=(a08*a10);
  a20=(a07*a05);
  a21=(a19+a20);
  a21=(a12*a21);
  a21=(a21*a04);
  a15=(a15+a21);
  a21=arg[2]? arg[2][8] : 0;
  a22=(a15*a21);
  a05=(a05*a10);
  a07=(a07*a08);
  a10=(a05+a07);
  a10=(a12*a10);
  a10=(a10*a01);
  a19=(a19-a20);
  a19=(a12*a19);
  a19=(a19*a02);
  a10=(a10+a19);
  a08=casadi_sq(a08);
  a17=(a17+a08);
  a17=(a12*a17);
  a17=(a16-a17);
  a17=(a17*a04);
  a10=(a10+a17);
  a17=arg[2]? arg[2][7] : 0;
  a19=(a10*a17);
  a22=(a22-a19);
  a22=(a00*a22);
  a19=4.3333333333333335e-02;
  a19=(a19*a11);
  a20=(a09*a19);
  a23=3.3333333333333333e-02;
  a23=(a23*a09);
  a24=(a11*a23);
  a20=(a20-a24);
  a22=(a22-a20);
  a20=arg[2]? arg[2][3] : 0;
  a22=(a22+a20);
  a03=(a03*a22);
  if (res[0]!=0) res[0][10]=a03;
  a03=30.;
  a22=arg[2]? arg[2][6] : 0;
  a10=(a10*a22);
  a08=(a08+a18);
  a08=(a12*a08);
  a16=(a16-a08);
  a16=(a16*a01);
  a13=(a13+a14);
  a13=(a12*a13);
  a13=(a13*a02);
  a16=(a16+a13);
  a05=(a05-a07);
  a12=(a12*a05);
  a12=(a12*a04);
  a16=(a16+a12);
  a21=(a16*a21);
  a10=(a10-a21);
  a10=(a00*a10);
  a21=1.6666666666666670e-02;
  a21=(a21*a06);
  a11=(a11*a21);
  a19=(a06*a19);
  a11=(a11-a19);
  a10=(a10-a11);
  a11=arg[2]? arg[2][4] : 0;
  a10=(a10+a11);
  a03=(a03*a10);
  if (res[0]!=0) res[0][11]=a03;
  a03=2.3076923076923077e+01;
  a16=(a16*a17);
  a15=(a15*a22);
  a16=(a16-a15);
  a00=(a00*a16);
  a06=(a06*a23);
  a09=(a09*a21);
  a06=(a06-a09);
  a00=(a00-a06);
  a06=arg[2]? arg[2][5] : 0;
  a00=(a00+a06);
  a03=(a03*a00);
  if (res[0]!=0) res[0][12]=a03;
  a03=arg[0]? arg[0][17] : 0;
  a00=(a03*a04);
  a06=arg[0]? arg[0][18] : 0;
  a09=(a06*a02);
  a00=(a00-a09);
  if (res[0]!=0) res[0][13]=a00;
  a06=(a06*a01);
  a00=arg[0]? arg[0][16] : 0;
  a04=(a00*a04);
  a06=(a06-a04);
  if (res[0]!=0) res[0][14]=a06;
  a00=(a00*a02);
  a03=(a03*a01);
  a00=(a00-a03);
  if (res[0]!=0) res[0][15]=a00;
  a00=arg[0]? arg[0][19] : 0;
  if (res[0]!=0) res[0][16]=a00;
  a00=arg[0]? arg[0][20] : 0;
  if (res[0]!=0) res[0][17]=a00;
  a00=arg[0]? arg[0][21] : 0;
  if (res[0]!=0) res[0][18]=a00;
  a00=arg[0]? arg[0][22] : 0;
  if (res[0]!=0) res[0][19]=a00;
  a00=arg[0]? arg[0][23] : 0;
  if (res[0]!=0) res[0][20]=a00;
  a00=arg[0]? arg[0][24] : 0;
  if (res[0]!=0) res[0][21]=a00;
  a00=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][22]=a00;
  a00=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][23]=a00;
  a00=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][24]=a00;
  a00=arg[0]? arg[0][26] : 0;
  if (res[0]!=0) res[0][25]=a00;
  a00=arg[1]? arg[1][3] : 0;
  if (res[0]!=0) res[0][26]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int distributed_single_cable_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int distributed_single_cable_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int distributed_single_cable_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void distributed_single_cable_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int distributed_single_cable_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void distributed_single_cable_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void distributed_single_cable_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void distributed_single_cable_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int distributed_single_cable_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int distributed_single_cable_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real distributed_single_cable_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* distributed_single_cable_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* distributed_single_cable_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* distributed_single_cable_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* distributed_single_cable_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int distributed_single_cable_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int distributed_single_cable_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
