/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) distributed_single_cable_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {27, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {9, 1, 1};
static const casadi_int casadi_s3[3] = {31, 1, 1};

/* distributed_single_cable_expl_vde_adj:(i0[27],i1[27],i2[4],i3[9])->(o0[31]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[0]? arg[0][9] : 0;
  a01=2.;
  a02=arg[0]? arg[0][14] : 0;
  a03=arg[3]? arg[3][7] : 0;
  a04=arg[0]? arg[0][25] : 0;
  a05=2.3076923076923077e+01;
  a06=arg[1]? arg[1][12] : 0;
  a05=(a05*a06);
  a06=(a04*a05);
  a07=(a03*a06);
  a08=arg[3]? arg[3][8] : 0;
  a09=30.;
  a10=arg[1]? arg[1][11] : 0;
  a09=(a09*a10);
  a10=(a04*a09);
  a11=(a08*a10);
  a07=(a07-a11);
  a11=(a02*a07);
  a11=(a01*a11);
  a12=(a00*a11);
  a13=arg[0]? arg[0][8] : 0;
  a14=arg[0]? arg[0][15] : 0;
  a15=(a14*a07);
  a15=(a01*a15);
  a16=(a13*a15);
  a12=(a12-a16);
  a16=arg[0]? arg[0][7] : 0;
  a17=arg[3]? arg[3][6] : 0;
  a10=(a17*a10);
  a18=5.9999999999999986e+01;
  a19=arg[1]? arg[1][10] : 0;
  a18=(a18*a19);
  a19=(a04*a18);
  a20=(a03*a19);
  a10=(a10-a20);
  a20=(a02*a10);
  a20=(a01*a20);
  a21=(a16*a20);
  a12=(a12-a21);
  a21=arg[0]? arg[0][13] : 0;
  a22=(a21*a10);
  a22=(a01*a22);
  a23=(a13*a22);
  a12=(a12+a23);
  a19=(a08*a19);
  a06=(a17*a06);
  a19=(a19-a06);
  a06=(a14*a19);
  a06=(a01*a06);
  a23=(a16*a06);
  a12=(a12+a23);
  a23=(a21*a19);
  a23=(a01*a23);
  a24=(a00*a23);
  a12=(a12-a24);
  a24=arg[0]? arg[0][12] : 0;
  a25=5.0000000000000000e-01;
  a26=arg[1]? arg[1][9] : 0;
  a26=(a25*a26);
  a27=(a24*a26);
  a12=(a12+a27);
  a27=arg[0]? arg[0][11] : 0;
  a28=arg[1]? arg[1][8] : 0;
  a28=(a25*a28);
  a29=(a27*a28);
  a12=(a12+a29);
  a29=arg[0]? arg[0][10] : 0;
  a30=arg[1]? arg[1][7] : 0;
  a30=(a25*a30);
  a31=(a29*a30);
  a12=(a12+a31);
  if (res[0]!=0) res[0][6]=a12;
  a12=(a00*a15);
  a31=(a13*a11);
  a12=(a12+a31);
  a31=(a16+a16);
  a32=(a14*a10);
  a32=(a01*a32);
  a33=(a31*a32);
  a12=(a12-a33);
  a33=arg[0]? arg[0][6] : 0;
  a34=(a33*a20);
  a12=(a12-a34);
  a34=(a00*a22);
  a12=(a12+a34);
  a34=(a33*a06);
  a12=(a12+a34);
  a34=(a02*a19);
  a34=(a01*a34);
  a31=(a31*a34);
  a12=(a12-a31);
  a31=(a13*a23);
  a12=(a12+a31);
  a31=(a27*a26);
  a12=(a12+a31);
  a31=(a24*a28);
  a12=(a12-a31);
  a31=arg[1]? arg[1][6] : 0;
  a25=(a25*a31);
  a31=(a29*a25);
  a12=(a12-a31);
  if (res[0]!=0) res[0][7]=a12;
  a12=(a16*a11);
  a31=(a33*a15);
  a12=(a12-a31);
  a31=(a13+a13);
  a35=(a21*a07);
  a35=(a01*a35);
  a36=(a31*a35);
  a12=(a12-a36);
  a31=(a31*a32);
  a12=(a12-a31);
  a31=(a00*a20);
  a12=(a12+a31);
  a31=(a33*a22);
  a12=(a12+a31);
  a31=(a00*a06);
  a12=(a12+a31);
  a31=(a16*a23);
  a12=(a12+a31);
  a31=(a29*a26);
  a12=(a12-a31);
  a31=(a24*a30);
  a12=(a12+a31);
  a31=(a27*a25);
  a12=(a12-a31);
  if (res[0]!=0) res[0][8]=a12;
  a15=(a16*a15);
  a11=(a33*a11);
  a15=(a15+a11);
  a11=(a00+a00);
  a35=(a11*a35);
  a15=(a15-a35);
  a20=(a13*a20);
  a15=(a15+a20);
  a22=(a16*a22);
  a15=(a15+a22);
  a06=(a13*a06);
  a15=(a15+a06);
  a11=(a11*a34);
  a15=(a15-a11);
  a23=(a33*a23);
  a15=(a15-a23);
  a23=(a29*a28);
  a15=(a15+a23);
  a23=(a27*a30);
  a15=(a15-a23);
  a23=(a24*a25);
  a15=(a15-a23);
  if (res[0]!=0) res[0][9]=a15;
  a15=4.3333333333333335e-02;
  a23=(a15*a24);
  a11=(a23*a09);
  a34=3.3333333333333333e-02;
  a06=(a34*a27);
  a22=(a06*a05);
  a11=(a11-a22);
  a22=1.6666666666666670e-02;
  a20=(a27*a05);
  a35=(a24*a09);
  a20=(a20-a35);
  a20=(a22*a20);
  a11=(a11+a20);
  a20=(a13*a26);
  a11=(a11-a20);
  a20=(a00*a28);
  a11=(a11+a20);
  a20=(a33*a30);
  a11=(a11+a20);
  a20=(a16*a25);
  a11=(a11-a20);
  if (res[0]!=0) res[0][10]=a11;
  a22=(a22*a29);
  a11=(a22*a05);
  a24=(a24*a18);
  a20=(a29*a05);
  a24=(a24-a20);
  a34=(a34*a24);
  a11=(a11+a34);
  a23=(a23*a18);
  a11=(a11-a23);
  a23=(a16*a26);
  a11=(a11+a23);
  a23=(a33*a28);
  a11=(a11+a23);
  a23=(a00*a30);
  a11=(a11-a23);
  a23=(a13*a25);
  a11=(a11-a23);
  if (res[0]!=0) res[0][11]=a11;
  a06=(a06*a18);
  a22=(a22*a09);
  a06=(a06-a22);
  a29=(a29*a09);
  a27=(a27*a18);
  a29=(a29-a27);
  a15=(a15*a29);
  a06=(a06+a15);
  a26=(a33*a26);
  a06=(a06+a26);
  a28=(a16*a28);
  a06=(a06-a28);
  a30=(a13*a30);
  a06=(a06+a30);
  a25=(a00*a25);
  a06=(a06-a25);
  if (res[0]!=0) res[0][12]=a06;
  a06=arg[0]? arg[0][18] : 0;
  a25=arg[1]? arg[1][14] : 0;
  a30=(a06*a25);
  a28=arg[0]? arg[0][17] : 0;
  a26=arg[1]? arg[1][15] : 0;
  a15=(a28*a26);
  a30=(a30-a15);
  a15=1.;
  a29=casadi_sq(a13);
  a27=casadi_sq(a00);
  a22=(a29+a27);
  a22=(a01*a22);
  a22=(a15-a22);
  a11=(a22*a07);
  a30=(a30+a11);
  a11=(a16*a00);
  a23=(a33*a13);
  a34=(a11+a23);
  a34=(a01*a34);
  a24=(a34*a10);
  a30=(a30+a24);
  a24=(a16*a13);
  a20=(a33*a00);
  a35=(a24-a20);
  a35=(a01*a35);
  a12=(a35*a19);
  a30=(a30+a12);
  a12=arg[1]? arg[1][3] : 0;
  a31=(a04*a12);
  a30=(a30-a31);
  if (res[0]!=0) res[0][13]=a30;
  a30=arg[0]? arg[0][16] : 0;
  a31=(a30*a26);
  a32=arg[1]? arg[1][13] : 0;
  a06=(a06*a32);
  a31=(a31-a06);
  a24=(a24+a20);
  a24=(a01*a24);
  a20=(a24*a07);
  a31=(a31+a20);
  a13=(a13*a00);
  a33=(a33*a16);
  a00=(a13-a33);
  a00=(a01*a00);
  a20=(a00*a10);
  a31=(a31+a20);
  a16=casadi_sq(a16);
  a27=(a16+a27);
  a27=(a01*a27);
  a27=(a15-a27);
  a20=(a27*a19);
  a31=(a31+a20);
  a20=arg[1]? arg[1][4] : 0;
  a06=(a04*a20);
  a31=(a31-a06);
  if (res[0]!=0) res[0][14]=a31;
  a28=(a28*a32);
  a30=(a30*a25);
  a28=(a28-a30);
  a11=(a11-a23);
  a11=(a01*a11);
  a07=(a11*a07);
  a28=(a28+a07);
  a16=(a16+a29);
  a16=(a01*a16);
  a15=(a15-a16);
  a10=(a15*a10);
  a28=(a28+a10);
  a13=(a13+a33);
  a01=(a01*a13);
  a19=(a01*a19);
  a28=(a28+a19);
  a19=arg[1]? arg[1][5] : 0;
  a04=(a04*a19);
  a28=(a28-a04);
  if (res[0]!=0) res[0][15]=a28;
  a28=(a02*a26);
  a04=(a14*a25);
  a28=(a28-a04);
  if (res[0]!=0) res[0][16]=a28;
  a28=(a14*a32);
  a26=(a21*a26);
  a28=(a28-a26);
  if (res[0]!=0) res[0][17]=a28;
  a25=(a21*a25);
  a32=(a02*a32);
  a25=(a25-a32);
  if (res[0]!=0) res[0][18]=a25;
  a25=arg[1]? arg[1][16] : 0;
  if (res[0]!=0) res[0][19]=a25;
  a25=arg[1]? arg[1][17] : 0;
  if (res[0]!=0) res[0][20]=a25;
  a25=arg[1]? arg[1][18] : 0;
  if (res[0]!=0) res[0][21]=a25;
  a25=arg[1]? arg[1][19] : 0;
  if (res[0]!=0) res[0][22]=a25;
  a25=arg[1]? arg[1][20] : 0;
  if (res[0]!=0) res[0][23]=a25;
  a25=arg[1]? arg[1][21] : 0;
  if (res[0]!=0) res[0][24]=a25;
  a22=(a22*a21);
  a24=(a24*a02);
  a22=(a22+a24);
  a11=(a11*a14);
  a22=(a22+a11);
  a11=(a22*a03);
  a35=(a35*a21);
  a27=(a27*a02);
  a35=(a35+a27);
  a01=(a01*a14);
  a35=(a35+a01);
  a01=(a35*a17);
  a11=(a11-a01);
  a11=(a11*a05);
  a34=(a34*a21);
  a00=(a00*a02);
  a34=(a34+a00);
  a15=(a15*a14);
  a34=(a34+a15);
  a17=(a34*a17);
  a22=(a22*a08);
  a17=(a17-a22);
  a17=(a17*a09);
  a11=(a11+a17);
  a35=(a35*a08);
  a34=(a34*a03);
  a35=(a35-a34);
  a35=(a35*a18);
  a11=(a11+a35);
  a14=(a14*a19);
  a11=(a11-a14);
  a02=(a02*a20);
  a11=(a11-a02);
  a21=(a21*a12);
  a11=(a11-a21);
  if (res[0]!=0) res[0][25]=a11;
  a11=arg[1]? arg[1][25] : 0;
  if (res[0]!=0) res[0][26]=a11;
  a11=arg[1]? arg[1][22] : 0;
  if (res[0]!=0) res[0][27]=a11;
  a11=arg[1]? arg[1][23] : 0;
  if (res[0]!=0) res[0][28]=a11;
  a11=arg[1]? arg[1][24] : 0;
  if (res[0]!=0) res[0][29]=a11;
  a11=arg[1]? arg[1][26] : 0;
  if (res[0]!=0) res[0][30]=a11;
  return 0;
}

CASADI_SYMBOL_EXPORT int distributed_single_cable_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int distributed_single_cable_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int distributed_single_cable_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void distributed_single_cable_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int distributed_single_cable_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void distributed_single_cable_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void distributed_single_cable_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void distributed_single_cable_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int distributed_single_cable_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int distributed_single_cable_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real distributed_single_cable_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* distributed_single_cable_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* distributed_single_cable_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* distributed_single_cable_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* distributed_single_cable_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int distributed_single_cable_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int distributed_single_cable_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
