/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) multi_payload_model_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {43, 1, 1};
static const casadi_int casadi_s1[3] = {12, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};

/* multi_payload_model_expl_ode_fun:(i0[43],i1[12],i2[0])->(o0[43]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;
  casadi_real a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a70, a71;
  casadi_real a72, a73, a74, a75, a76, a77, a78, a79, a80, a81, a82, a83;
  casadi_real a84, a85, a86, a87, a88, a89, a90, a91, a92, a93, a94, a95;
  a00=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[1]? arg[1][0] : 0;
  a01=2.;
  a02=arg[0]? arg[0][32] : 0;
  a03=arg[0]? arg[0][34] : 0;
  a04=(a02*a03);
  a05=arg[0]? arg[0][31] : 0;
  a06=arg[0]? arg[0][33] : 0;
  a07=(a05*a06);
  a04=(a04+a07);
  a04=(a01*a04);
  a04=(a00*a04);
  a07=1.5349999999999999e+00;
  a08=arg[0]? arg[0][7] : 0;
  a09=arg[0]? arg[0][8] : 0;
  a10=(a08*a09);
  a11=arg[0]? arg[0][6] : 0;
  a12=arg[0]? arg[0][9] : 0;
  a13=(a11*a12);
  a14=(a10-a13);
  a14=(a01*a14);
  a15=arg[0]? arg[0][10] : 0;
  a16=arg[0]? arg[0][11] : 0;
  a17=(a15*a16);
  a18=(a14*a17);
  a19=1.;
  a20=casadi_sq(a09);
  a21=casadi_sq(a12);
  a22=(a20+a21);
  a22=(a01*a22);
  a22=(a19-a22);
  a23=casadi_sq(a16);
  a24=arg[0]? arg[0][12] : 0;
  a25=casadi_sq(a24);
  a23=(a23+a25);
  a25=(a22*a23);
  a18=(a18-a25);
  a25=(a08*a12);
  a26=(a11*a09);
  a27=(a25+a26);
  a27=(a01*a27);
  a28=(a15*a24);
  a29=(a27*a28);
  a18=(a18+a29);
  a29=2.0597322348094751e-01;
  a30=(a07*a18);
  a30=(a04-a30);
  a31=arg[0]? arg[0][17] : 0;
  a32=arg[0]? arg[0][16] : 0;
  a33=arg[0]? arg[0][14] : 0;
  a34=(a32*a33);
  a35=arg[0]? arg[0][13] : 0;
  a36=(a31*a35);
  a34=(a34-a36);
  a36=(a31*a34);
  a37=arg[0]? arg[0][18] : 0;
  a38=(a37*a35);
  a39=arg[0]? arg[0][15] : 0;
  a40=(a32*a39);
  a38=(a38-a40);
  a40=(a37*a38);
  a36=(a36-a40);
  a36=(a07*a36);
  a30=(a30+a36);
  a40=(a14*a30);
  a41=casadi_sq(a08);
  a21=(a41+a21);
  a21=(a01*a21);
  a21=(a19-a21);
  a42=(a06*a03);
  a43=(a05*a02);
  a42=(a42-a43);
  a42=(a01*a42);
  a42=(a00*a42);
  a43=(a21*a17);
  a10=(a10+a13);
  a10=(a01*a10);
  a13=(a10*a23);
  a43=(a43-a13);
  a13=(a09*a12);
  a44=(a11*a08);
  a45=(a13-a44);
  a45=(a01*a45);
  a46=(a45*a28);
  a43=(a43+a46);
  a46=(a07*a43);
  a46=(a42-a46);
  a47=(a31*a39);
  a48=(a37*a33);
  a47=(a47-a48);
  a37=(a37*a47);
  a48=(a32*a34);
  a37=(a37-a48);
  a37=(a07*a37);
  a46=(a46+a37);
  a48=(a21*a46);
  a40=(a40+a48);
  a13=(a13+a44);
  a13=(a01*a13);
  a44=casadi_sq(a05);
  a48=casadi_sq(a02);
  a44=(a44-a48);
  a48=casadi_sq(a06);
  a44=(a44-a48);
  a48=casadi_sq(a03);
  a44=(a44+a48);
  a00=(a00*a44);
  a44=1.5058350000000001e+01;
  a00=(a00-a44);
  a17=(a13*a17);
  a25=(a25-a26);
  a25=(a01*a25);
  a23=(a25*a23);
  a17=(a17-a23);
  a41=(a41+a20);
  a41=(a01*a41);
  a19=(a19-a41);
  a28=(a19*a28);
  a17=(a17+a28);
  a28=(a07*a17);
  a28=(a00-a28);
  a32=(a32*a38);
  a31=(a31*a47);
  a32=(a32-a31);
  a32=(a07*a32);
  a28=(a28+a32);
  a31=(a13*a28);
  a40=(a40+a31);
  a31=1.3833333333333334e-01;
  a41=(a31*a16);
  a20=(a15*a41);
  a31=(a31*a15);
  a23=(a16*a31);
  a20=(a20-a23);
  a40=(a40-a20);
  a20=-5.0000000000000011e-01;
  a23=arg[1]? arg[1][4] : 0;
  a26=arg[0]? arg[0][36] : 0;
  a48=arg[0]? arg[0][38] : 0;
  a49=(a26*a48);
  a50=arg[0]? arg[0][35] : 0;
  a51=arg[0]? arg[0][37] : 0;
  a52=(a50*a51);
  a49=(a49+a52);
  a49=(a01*a49);
  a49=(a23*a49);
  a52=8.6602540378443860e-01;
  a53=(a52*a15);
  a54=(a20*a16);
  a53=(a53-a54);
  a55=(a16*a53);
  a56=(a20*a24);
  a57=(a24*a56);
  a55=(a55-a57);
  a58=(a22*a55);
  a59=(a52*a24);
  a60=(a24*a59);
  a53=(a15*a53);
  a60=(a60+a53);
  a53=(a14*a60);
  a58=(a58-a53);
  a56=(a15*a56);
  a59=(a16*a59);
  a59=(a56+a59);
  a53=(a27*a59);
  a58=(a58+a53);
  a53=(a07*a58);
  a53=(a49-a53);
  a61=arg[0]? arg[0][23] : 0;
  a62=arg[0]? arg[0][22] : 0;
  a63=arg[0]? arg[0][20] : 0;
  a64=(a62*a63);
  a65=arg[0]? arg[0][19] : 0;
  a66=(a61*a65);
  a64=(a64-a66);
  a66=(a61*a64);
  a67=arg[0]? arg[0][24] : 0;
  a68=(a67*a65);
  a69=arg[0]? arg[0][21] : 0;
  a70=(a62*a69);
  a68=(a68-a70);
  a70=(a67*a68);
  a66=(a66-a70);
  a66=(a07*a66);
  a53=(a53+a66);
  a70=(a14*a53);
  a71=(a51*a48);
  a72=(a50*a26);
  a71=(a71-a72);
  a71=(a01*a71);
  a71=(a23*a71);
  a72=(a10*a55);
  a73=(a21*a60);
  a72=(a72-a73);
  a73=(a45*a59);
  a72=(a72+a73);
  a73=(a07*a72);
  a73=(a71-a73);
  a74=(a61*a69);
  a75=(a67*a63);
  a74=(a74-a75);
  a67=(a67*a74);
  a75=(a62*a64);
  a67=(a67-a75);
  a67=(a07*a67);
  a73=(a73+a67);
  a75=(a21*a73);
  a70=(a70+a75);
  a75=casadi_sq(a50);
  a76=casadi_sq(a26);
  a75=(a75-a76);
  a76=casadi_sq(a51);
  a75=(a75-a76);
  a76=casadi_sq(a48);
  a75=(a75+a76);
  a23=(a23*a75);
  a23=(a23-a44);
  a55=(a25*a55);
  a60=(a13*a60);
  a55=(a55-a60);
  a59=(a19*a59);
  a55=(a55+a59);
  a59=(a07*a55);
  a59=(a23-a59);
  a62=(a62*a68);
  a61=(a61*a74);
  a62=(a62-a61);
  a62=(a07*a62);
  a59=(a59+a62);
  a61=(a13*a59);
  a70=(a70+a61);
  a70=(a20*a70);
  a61=(a22*a53);
  a60=(a10*a73);
  a61=(a61+a60);
  a60=(a25*a59);
  a61=(a61+a60);
  a61=(a52*a61);
  a70=(a70-a61);
  a40=(a40+a70);
  a70=arg[1]? arg[1][8] : 0;
  a61=arg[0]? arg[0][40] : 0;
  a60=arg[0]? arg[0][42] : 0;
  a75=(a61*a60);
  a76=arg[0]? arg[0][39] : 0;
  a77=arg[0]? arg[0][41] : 0;
  a78=(a76*a77);
  a75=(a75+a78);
  a75=(a01*a75);
  a75=(a70*a75);
  a78=-8.6602540378443860e-01;
  a79=(a78*a15);
  a79=(a79-a54);
  a54=(a16*a79);
  a54=(a54-a57);
  a57=(a22*a54);
  a80=(a78*a24);
  a81=(a24*a80);
  a79=(a15*a79);
  a81=(a81+a79);
  a79=(a14*a81);
  a57=(a57-a79);
  a80=(a16*a80);
  a56=(a56+a80);
  a80=(a27*a56);
  a57=(a57+a80);
  a80=(a07*a57);
  a80=(a75-a80);
  a79=arg[0]? arg[0][29] : 0;
  a82=arg[0]? arg[0][28] : 0;
  a83=arg[0]? arg[0][26] : 0;
  a84=(a82*a83);
  a85=arg[0]? arg[0][25] : 0;
  a86=(a79*a85);
  a84=(a84-a86);
  a86=(a79*a84);
  a87=arg[0]? arg[0][30] : 0;
  a88=(a87*a85);
  a89=arg[0]? arg[0][27] : 0;
  a90=(a82*a89);
  a88=(a88-a90);
  a90=(a87*a88);
  a86=(a86-a90);
  a86=(a07*a86);
  a80=(a80+a86);
  a90=(a14*a80);
  a91=(a77*a60);
  a92=(a76*a61);
  a91=(a91-a92);
  a01=(a01*a91);
  a01=(a70*a01);
  a91=(a10*a54);
  a92=(a21*a81);
  a91=(a91-a92);
  a92=(a45*a56);
  a91=(a91+a92);
  a92=(a07*a91);
  a92=(a01-a92);
  a93=(a79*a89);
  a94=(a87*a83);
  a93=(a93-a94);
  a87=(a87*a93);
  a94=(a82*a84);
  a87=(a87-a94);
  a87=(a07*a87);
  a92=(a92+a87);
  a94=(a21*a92);
  a90=(a90+a94);
  a94=casadi_sq(a76);
  a95=casadi_sq(a61);
  a94=(a94-a95);
  a95=casadi_sq(a77);
  a94=(a94-a95);
  a95=casadi_sq(a60);
  a94=(a94+a95);
  a70=(a70*a94);
  a70=(a70-a44);
  a54=(a25*a54);
  a81=(a13*a81);
  a54=(a54-a81);
  a56=(a19*a56);
  a54=(a54+a56);
  a56=(a07*a54);
  a56=(a70-a56);
  a82=(a82*a88);
  a79=(a79*a93);
  a82=(a82-a79);
  a82=(a07*a82);
  a56=(a56+a82);
  a79=(a13*a56);
  a90=(a90+a79);
  a90=(a20*a90);
  a79=(a22*a80);
  a81=(a10*a92);
  a79=(a79+a81);
  a81=(a25*a56);
  a79=(a79+a81);
  a79=(a78*a79);
  a90=(a90-a79);
  a40=(a40+a90);
  a29=(a29*a40);
  a40=(a14*a29);
  a90=4.0969614202799592e-01;
  a31=(a24*a31);
  a79=2.5000000000000000e-01;
  a79=(a79*a24);
  a81=(a15*a79);
  a31=(a31-a81);
  a30=(a27*a30);
  a46=(a45*a46);
  a30=(a30+a46);
  a28=(a19*a28);
  a30=(a30+a28);
  a31=(a31+a30);
  a53=(a27*a53);
  a73=(a45*a73);
  a53=(a53+a73);
  a59=(a19*a59);
  a53=(a53+a59);
  a59=(a20*a53);
  a31=(a31+a59);
  a80=(a27*a80);
  a92=(a45*a92);
  a80=(a80+a92);
  a56=(a19*a56);
  a80=(a80+a56);
  a56=(a20*a80);
  a31=(a31+a56);
  a90=(a90*a31);
  a31=(a27*a90);
  a40=(a40+a31);
  a31=(a18+a40);
  a31=(a07*a31);
  a31=(a04-a31);
  a31=(a31+a36);
  a31=(a31+a49);
  a36=(a20*a29);
  a14=(a14*a36);
  a56=(a52*a29);
  a92=(a22*a56);
  a92=(a14-a92);
  a59=4.0969614202799598e-01;
  a53=(a52*a53);
  a79=(a16*a79);
  a41=(a24*a41);
  a79=(a79-a41);
  a53=(a53-a79);
  a80=(a78*a80);
  a53=(a53+a80);
  a59=(a59*a53);
  a52=(a52*a59);
  a20=(a20*a90);
  a52=(a52+a20);
  a53=(a27*a52);
  a92=(a92+a53);
  a53=(a58+a92);
  a53=(a07*a53);
  a31=(a31-a53);
  a31=(a31+a66);
  a31=(a31+a75);
  a66=(a78*a29);
  a22=(a22*a66);
  a14=(a14-a22);
  a78=(a78*a59);
  a78=(a78+a20);
  a27=(a27*a78);
  a14=(a14+a27);
  a27=(a57+a14);
  a27=(a07*a27);
  a31=(a31-a27);
  a31=(a31+a86);
  a86=5.6050000000000004e+00;
  a31=(a31/a86);
  if (res[0]!=0) res[0][3]=a31;
  a27=(a21*a29);
  a20=(a45*a90);
  a27=(a27+a20);
  a20=(a43+a27);
  a20=(a07*a20);
  a20=(a42-a20);
  a20=(a20+a37);
  a20=(a20+a71);
  a21=(a21*a36);
  a37=(a10*a56);
  a37=(a21-a37);
  a22=(a45*a52);
  a37=(a37+a22);
  a22=(a72+a37);
  a22=(a07*a22);
  a20=(a20-a22);
  a20=(a20+a67);
  a20=(a20+a01);
  a10=(a10*a66);
  a21=(a21-a10);
  a45=(a45*a78);
  a21=(a21+a45);
  a45=(a91+a21);
  a45=(a07*a45);
  a20=(a20-a45);
  a20=(a20+a87);
  a20=(a20/a86);
  if (res[0]!=0) res[0][4]=a20;
  a87=(a13*a29);
  a45=(a19*a90);
  a87=(a87+a45);
  a45=(a17+a87);
  a45=(a07*a45);
  a45=(a00-a45);
  a45=(a45+a32);
  a45=(a45+a23);
  a13=(a13*a36);
  a56=(a25*a56);
  a56=(a13-a56);
  a52=(a19*a52);
  a56=(a56+a52);
  a52=(a55+a56);
  a52=(a07*a52);
  a45=(a45-a52);
  a45=(a45+a62);
  a45=(a45+a70);
  a25=(a25*a66);
  a13=(a13-a25);
  a19=(a19*a78);
  a13=(a13+a19);
  a19=(a54+a13);
  a07=(a07*a19);
  a45=(a45-a07);
  a45=(a45+a82);
  a82=9.8100000000000005e+00;
  a45=(a45-a82);
  a45=(a45/a86);
  if (res[0]!=0) res[0][5]=a45;
  a86=5.0000000000000000e-01;
  a82=(a08*a15);
  a07=(a09*a16);
  a82=(a82+a07);
  a07=(a12*a24);
  a82=(a82+a07);
  a82=(a86*a82);
  a82=(-a82);
  if (res[0]!=0) res[0][6]=a82;
  a82=(a11*a15);
  a07=(a12*a16);
  a82=(a82-a07);
  a07=(a09*a24);
  a82=(a82+a07);
  a82=(a86*a82);
  if (res[0]!=0) res[0][7]=a82;
  a12=(a12*a15);
  a82=(a11*a16);
  a12=(a12+a82);
  a82=(a08*a24);
  a12=(a12-a82);
  a12=(a86*a12);
  if (res[0]!=0) res[0][8]=a12;
  a08=(a08*a16);
  a09=(a09*a15);
  a08=(a08-a09);
  a11=(a11*a24);
  a08=(a08+a11);
  a08=(a86*a08);
  if (res[0]!=0) res[0][9]=a08;
  if (res[0]!=0) res[0][10]=a59;
  a90=(-a90);
  if (res[0]!=0) res[0][11]=a90;
  if (res[0]!=0) res[0][12]=a29;
  if (res[0]!=0) res[0][13]=a47;
  if (res[0]!=0) res[0][14]=a38;
  if (res[0]!=0) res[0][15]=a34;
  a17=(a45+a17);
  a17=(a17+a87);
  a87=6.5146579804560267e-01;
  a00=(a87*a00);
  a17=(a17-a00);
  a00=(a33*a17);
  a43=(a20+a43);
  a43=(a43+a27);
  a42=(a87*a42);
  a43=(a43-a42);
  a42=(a39*a43);
  a00=(a00-a42);
  if (res[0]!=0) res[0][16]=a00;
  a18=(a31+a18);
  a18=(a18+a40);
  a04=(a87*a04);
  a18=(a18-a04);
  a39=(a39*a18);
  a17=(a35*a17);
  a39=(a39-a17);
  if (res[0]!=0) res[0][17]=a39;
  a35=(a35*a43);
  a33=(a33*a18);
  a35=(a35-a33);
  if (res[0]!=0) res[0][18]=a35;
  if (res[0]!=0) res[0][19]=a74;
  if (res[0]!=0) res[0][20]=a68;
  if (res[0]!=0) res[0][21]=a64;
  a55=(a45+a55);
  a55=(a55+a56);
  a23=(a87*a23);
  a55=(a55-a23);
  a23=(a63*a55);
  a72=(a20+a72);
  a72=(a72+a37);
  a71=(a87*a71);
  a72=(a72-a71);
  a71=(a69*a72);
  a23=(a23-a71);
  if (res[0]!=0) res[0][22]=a23;
  a58=(a31+a58);
  a58=(a58+a92);
  a49=(a87*a49);
  a58=(a58-a49);
  a69=(a69*a58);
  a55=(a65*a55);
  a69=(a69-a55);
  if (res[0]!=0) res[0][23]=a69;
  a65=(a65*a72);
  a63=(a63*a58);
  a65=(a65-a63);
  if (res[0]!=0) res[0][24]=a65;
  if (res[0]!=0) res[0][25]=a93;
  if (res[0]!=0) res[0][26]=a88;
  if (res[0]!=0) res[0][27]=a84;
  a45=(a45+a54);
  a45=(a45+a13);
  a70=(a87*a70);
  a45=(a45-a70);
  a70=(a83*a45);
  a20=(a20+a91);
  a20=(a20+a21);
  a01=(a87*a01);
  a20=(a20-a01);
  a01=(a89*a20);
  a70=(a70-a01);
  if (res[0]!=0) res[0][28]=a70;
  a31=(a31+a57);
  a31=(a31+a14);
  a87=(a87*a75);
  a31=(a31-a87);
  a89=(a89*a31);
  a45=(a85*a45);
  a89=(a89-a45);
  if (res[0]!=0) res[0][29]=a89;
  a85=(a85*a20);
  a83=(a83*a31);
  a85=(a85-a83);
  if (res[0]!=0) res[0][30]=a85;
  a85=arg[1]? arg[1][1] : 0;
  a83=(a02*a85);
  a31=arg[1]? arg[1][2] : 0;
  a20=(a06*a31);
  a83=(a83+a20);
  a20=arg[1]? arg[1][3] : 0;
  a89=(a03*a20);
  a83=(a83+a89);
  a83=(a86*a83);
  a83=(-a83);
  if (res[0]!=0) res[0][31]=a83;
  a83=(a05*a85);
  a89=(a03*a31);
  a83=(a83-a89);
  a89=(a06*a20);
  a83=(a83+a89);
  a83=(a86*a83);
  if (res[0]!=0) res[0][32]=a83;
  a03=(a03*a85);
  a83=(a05*a31);
  a03=(a03+a83);
  a83=(a02*a20);
  a03=(a03-a83);
  a03=(a86*a03);
  if (res[0]!=0) res[0][33]=a03;
  a02=(a02*a31);
  a06=(a06*a85);
  a02=(a02-a06);
  a05=(a05*a20);
  a02=(a02+a05);
  a02=(a86*a02);
  if (res[0]!=0) res[0][34]=a02;
  a02=arg[1]? arg[1][5] : 0;
  a05=(a26*a02);
  a20=arg[1]? arg[1][6] : 0;
  a06=(a51*a20);
  a05=(a05+a06);
  a06=arg[1]? arg[1][7] : 0;
  a85=(a48*a06);
  a05=(a05+a85);
  a05=(a86*a05);
  a05=(-a05);
  if (res[0]!=0) res[0][35]=a05;
  a05=(a50*a02);
  a85=(a48*a20);
  a05=(a05-a85);
  a85=(a51*a06);
  a05=(a05+a85);
  a05=(a86*a05);
  if (res[0]!=0) res[0][36]=a05;
  a48=(a48*a02);
  a05=(a50*a20);
  a48=(a48+a05);
  a05=(a26*a06);
  a48=(a48-a05);
  a48=(a86*a48);
  if (res[0]!=0) res[0][37]=a48;
  a26=(a26*a20);
  a51=(a51*a02);
  a26=(a26-a51);
  a50=(a50*a06);
  a26=(a26+a50);
  a26=(a86*a26);
  if (res[0]!=0) res[0][38]=a26;
  a26=arg[1]? arg[1][9] : 0;
  a50=(a61*a26);
  a06=arg[1]? arg[1][10] : 0;
  a51=(a77*a06);
  a50=(a50+a51);
  a51=arg[1]? arg[1][11] : 0;
  a02=(a60*a51);
  a50=(a50+a02);
  a50=(a86*a50);
  a50=(-a50);
  if (res[0]!=0) res[0][39]=a50;
  a50=(a76*a26);
  a02=(a60*a06);
  a50=(a50-a02);
  a02=(a77*a51);
  a50=(a50+a02);
  a50=(a86*a50);
  if (res[0]!=0) res[0][40]=a50;
  a60=(a60*a26);
  a50=(a76*a06);
  a60=(a60+a50);
  a50=(a61*a51);
  a60=(a60-a50);
  a60=(a86*a60);
  if (res[0]!=0) res[0][41]=a60;
  a61=(a61*a06);
  a77=(a77*a26);
  a61=(a61-a77);
  a76=(a76*a51);
  a61=(a61+a76);
  a86=(a86*a61);
  if (res[0]!=0) res[0][42]=a86;
  return 0;
}

CASADI_SYMBOL_EXPORT int multi_payload_model_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int multi_payload_model_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int multi_payload_model_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void multi_payload_model_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int multi_payload_model_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void multi_payload_model_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void multi_payload_model_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void multi_payload_model_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int multi_payload_model_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int multi_payload_model_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real multi_payload_model_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* multi_payload_model_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* multi_payload_model_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* multi_payload_model_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* multi_payload_model_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int multi_payload_model_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int multi_payload_model_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
