/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) multi_payload_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {64, 1, 1};
static const casadi_int casadi_s1[3] = {12, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {3, 1, 1};
static const casadi_int casadi_s4[45] = 
  {76, 3, 0, 13, 26, 39, 12, 13,
  14, 18, 19, 20, 21, 25, 26, 27,
  31, 32, 33, 12, 13, 14, 18, 19,
  20, 21, 25, 26, 27, 37, 38, 39,
  12, 13, 14, 18, 19, 20, 21, 31,
  32, 33, 37, 38, 39};
static const casadi_int casadi_s5[3] = {3, 0, 1};

/* multi_payload_constr_h_fun_jac_uxt_zt:(i0[64],i1[12],i2[0],i3[0])->(o0[3],o1[76x3,39nz],o2[3x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29;
  a00=arg[0]? arg[0][0] : 0;
  a01=5.9999999999999998e-01;
  a02=1.;
  a03=2.;
  a04=arg[0]? arg[0][8] : 0;
  a05=casadi_sq(a04);
  a06=arg[0]? arg[0][9] : 0;
  a07=casadi_sq(a06);
  a05=(a05+a07);
  a05=(a03*a05);
  a05=(a02-a05);
  a08=(a01*a05);
  a08=(a00+a08);
  a09=1.5000000000000000e+00;
  a10=arg[0]? arg[0][13] : 0;
  a10=(a09*a10);
  a08=(a08-a10);
  a10=-2.9999999999999999e-01;
  a05=(a10*a05);
  a11=4.0000000000000002e-01;
  a12=arg[0]? arg[0][7] : 0;
  a13=(a12*a04);
  a14=arg[0]? arg[0][6] : 0;
  a15=(a14*a06);
  a16=(a13-a15);
  a16=(a03*a16);
  a17=(a11*a16);
  a17=(a05+a17);
  a17=(a00+a17);
  a18=arg[0]? arg[0][19] : 0;
  a18=(a09*a18);
  a17=(a17-a18);
  a18=(a08-a17);
  a19=casadi_sq(a18);
  a20=arg[0]? arg[0][1] : 0;
  a13=(a13+a15);
  a13=(a03*a13);
  a15=(a01*a13);
  a15=(a20+a15);
  a21=arg[0]? arg[0][14] : 0;
  a21=(a09*a21);
  a15=(a15-a21);
  a13=(a10*a13);
  a21=casadi_sq(a12);
  a21=(a21+a07);
  a21=(a03*a21);
  a02=(a02-a21);
  a21=(a11*a02);
  a21=(a13+a21);
  a21=(a20+a21);
  a07=arg[0]? arg[0][20] : 0;
  a07=(a09*a07);
  a21=(a21-a07);
  a07=(a15-a21);
  a22=casadi_sq(a07);
  a19=(a19+a22);
  a22=arg[0]? arg[0][2] : 0;
  a23=(a12*a06);
  a24=(a14*a04);
  a23=(a23-a24);
  a23=(a03*a23);
  a24=(a01*a23);
  a24=(a22+a24);
  a25=arg[0]? arg[0][15] : 0;
  a25=(a09*a25);
  a24=(a24-a25);
  a23=(a10*a23);
  a25=(a04*a06);
  a26=(a14*a12);
  a25=(a25+a26);
  a25=(a03*a25);
  a26=(a11*a25);
  a26=(a23+a26);
  a26=(a22+a26);
  a27=arg[0]? arg[0][21] : 0;
  a27=(a09*a27);
  a26=(a26-a27);
  a27=(a24-a26);
  a28=casadi_sq(a27);
  a19=(a19+a28);
  a28=4.8999999999999994e-01;
  a19=(a19-a28);
  if (res[0]!=0) res[0][0]=a19;
  a19=-4.0000000000000002e-01;
  a16=(a19*a16);
  a05=(a05+a16);
  a00=(a00+a05);
  a05=arg[0]? arg[0][25] : 0;
  a05=(a09*a05);
  a00=(a00-a05);
  a08=(a08-a00);
  a05=casadi_sq(a08);
  a02=(a19*a02);
  a13=(a13+a02);
  a20=(a20+a13);
  a13=arg[0]? arg[0][26] : 0;
  a13=(a09*a13);
  a20=(a20-a13);
  a15=(a15-a20);
  a13=casadi_sq(a15);
  a05=(a05+a13);
  a25=(a19*a25);
  a23=(a23+a25);
  a22=(a22+a23);
  a23=arg[0]? arg[0][27] : 0;
  a23=(a09*a23);
  a22=(a22-a23);
  a24=(a24-a22);
  a23=casadi_sq(a24);
  a05=(a05+a23);
  a05=(a05-a28);
  if (res[0]!=0) res[0][1]=a05;
  a17=(a17-a00);
  a00=casadi_sq(a17);
  a21=(a21-a20);
  a20=casadi_sq(a21);
  a00=(a00+a20);
  a26=(a26-a22);
  a22=casadi_sq(a26);
  a00=(a00+a22);
  a00=(a00-a28);
  if (res[0]!=0) res[0][2]=a00;
  a00=0.;
  if (res[1]!=0) res[1][0]=a00;
  if (res[1]!=0) res[1][1]=a00;
  if (res[1]!=0) res[1][2]=a00;
  a07=(a07+a07);
  a28=(a01*a07);
  a22=(a10*a07);
  a28=(a28-a22);
  a28=(a03*a28);
  a22=(a06*a28);
  a27=(a27+a27);
  a20=(a11*a27);
  a20=(a03*a20);
  a05=(a12*a20);
  a23=(a01*a27);
  a25=(a10*a27);
  a23=(a23-a25);
  a23=(a03*a23);
  a25=(a04*a23);
  a05=(a05+a25);
  a22=(a22-a05);
  a18=(a18+a18);
  a05=(a11*a18);
  a05=(a03*a05);
  a25=(a06*a05);
  a22=(a22+a25);
  if (res[1]!=0) res[1][3]=a22;
  a22=(a06*a23);
  a25=(a14*a20);
  a22=(a22-a25);
  a25=(a12+a12);
  a13=(a11*a07);
  a13=(a03*a13);
  a02=(a25*a13);
  a22=(a22+a02);
  a02=(a04*a28);
  a22=(a22+a02);
  a02=(a04*a05);
  a22=(a22-a02);
  if (res[1]!=0) res[1][4]=a22;
  a22=(a12*a28);
  a02=(a06*a20);
  a16=(a14*a23);
  a02=(a02+a16);
  a22=(a22-a02);
  a02=(a12*a05);
  a22=(a22-a02);
  a02=(a04+a04);
  a16=(a01*a18);
  a29=(a10*a18);
  a16=(a16-a29);
  a16=(a03*a16);
  a29=(a02*a16);
  a22=(a22-a29);
  if (res[1]!=0) res[1][5]=a22;
  a23=(a12*a23);
  a20=(a04*a20);
  a23=(a23-a20);
  a20=(a06+a06);
  a13=(a20*a13);
  a23=(a23+a13);
  a28=(a14*a28);
  a23=(a23+a28);
  a05=(a14*a05);
  a23=(a23+a05);
  a16=(a20*a16);
  a23=(a23-a16);
  if (res[1]!=0) res[1][6]=a23;
  a18=(a09*a18);
  a23=(-a18);
  if (res[1]!=0) res[1][7]=a23;
  a07=(a09*a07);
  a23=(-a07);
  if (res[1]!=0) res[1][8]=a23;
  a27=(a09*a27);
  a23=(-a27);
  if (res[1]!=0) res[1][9]=a23;
  if (res[1]!=0) res[1][10]=a18;
  if (res[1]!=0) res[1][11]=a07;
  if (res[1]!=0) res[1][12]=a27;
  if (res[1]!=0) res[1][13]=a00;
  if (res[1]!=0) res[1][14]=a00;
  if (res[1]!=0) res[1][15]=a00;
  a15=(a15+a15);
  a27=(a01*a15);
  a07=(a10*a15);
  a27=(a27-a07);
  a27=(a03*a27);
  a07=(a06*a27);
  a24=(a24+a24);
  a18=(a19*a24);
  a18=(a03*a18);
  a23=(a12*a18);
  a16=(a01*a24);
  a05=(a10*a24);
  a16=(a16-a05);
  a16=(a03*a16);
  a05=(a04*a16);
  a23=(a23+a05);
  a07=(a07-a23);
  a08=(a08+a08);
  a23=(a19*a08);
  a23=(a03*a23);
  a05=(a06*a23);
  a07=(a07+a05);
  if (res[1]!=0) res[1][16]=a07;
  a07=(a06*a16);
  a05=(a14*a18);
  a07=(a07-a05);
  a05=(a19*a15);
  a05=(a03*a05);
  a28=(a25*a05);
  a07=(a07+a28);
  a28=(a04*a27);
  a07=(a07+a28);
  a28=(a04*a23);
  a07=(a07-a28);
  if (res[1]!=0) res[1][17]=a07;
  a07=(a12*a27);
  a28=(a06*a18);
  a13=(a14*a16);
  a28=(a28+a13);
  a07=(a07-a28);
  a28=(a12*a23);
  a07=(a07-a28);
  a01=(a01*a08);
  a10=(a10*a08);
  a01=(a01-a10);
  a01=(a03*a01);
  a02=(a02*a01);
  a07=(a07-a02);
  if (res[1]!=0) res[1][18]=a07;
  a16=(a12*a16);
  a18=(a04*a18);
  a16=(a16-a18);
  a05=(a20*a05);
  a16=(a16+a05);
  a27=(a14*a27);
  a16=(a16+a27);
  a23=(a14*a23);
  a16=(a16+a23);
  a01=(a20*a01);
  a16=(a16-a01);
  if (res[1]!=0) res[1][19]=a16;
  a08=(a09*a08);
  a16=(-a08);
  if (res[1]!=0) res[1][20]=a16;
  a15=(a09*a15);
  a16=(-a15);
  if (res[1]!=0) res[1][21]=a16;
  a24=(a09*a24);
  a16=(-a24);
  if (res[1]!=0) res[1][22]=a16;
  if (res[1]!=0) res[1][23]=a08;
  if (res[1]!=0) res[1][24]=a15;
  if (res[1]!=0) res[1][25]=a24;
  if (res[1]!=0) res[1][26]=a00;
  if (res[1]!=0) res[1][27]=a00;
  if (res[1]!=0) res[1][28]=a00;
  a26=(a26+a26);
  a00=(a11*a26);
  a24=(a19*a26);
  a00=(a00-a24);
  a00=(a03*a00);
  a24=(a12*a00);
  a17=(a17+a17);
  a15=(a11*a17);
  a08=(a19*a17);
  a15=(a15-a08);
  a15=(a03*a15);
  a08=(a06*a15);
  a24=(a24-a08);
  if (res[1]!=0) res[1][29]=a24;
  a24=(a14*a00);
  a21=(a21+a21);
  a11=(a11*a21);
  a19=(a19*a21);
  a11=(a11-a19);
  a03=(a03*a11);
  a25=(a25*a03);
  a24=(a24-a25);
  a25=(a04*a15);
  a24=(a24+a25);
  if (res[1]!=0) res[1][30]=a24;
  a06=(a06*a00);
  a12=(a12*a15);
  a06=(a06+a12);
  if (res[1]!=0) res[1][31]=a06;
  a04=(a04*a00);
  a20=(a20*a03);
  a04=(a04-a20);
  a14=(a14*a15);
  a04=(a04-a14);
  if (res[1]!=0) res[1][32]=a04;
  a17=(a09*a17);
  a04=(-a17);
  if (res[1]!=0) res[1][33]=a04;
  a21=(a09*a21);
  a04=(-a21);
  if (res[1]!=0) res[1][34]=a04;
  a09=(a09*a26);
  a26=(-a09);
  if (res[1]!=0) res[1][35]=a26;
  if (res[1]!=0) res[1][36]=a17;
  if (res[1]!=0) res[1][37]=a21;
  if (res[1]!=0) res[1][38]=a09;
  return 0;
}

CASADI_SYMBOL_EXPORT int multi_payload_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int multi_payload_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int multi_payload_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void multi_payload_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int multi_payload_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void multi_payload_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void multi_payload_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void multi_payload_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int multi_payload_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int multi_payload_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real multi_payload_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* multi_payload_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* multi_payload_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* multi_payload_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* multi_payload_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int multi_payload_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int multi_payload_constr_h_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
