/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) kinodynamic_load_3cables_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {55, 1, 1};
static const casadi_int casadi_s1[3] = {12, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {3, 1, 1};

/* kinodynamic_load_3cables_constr_h_fun:(i0[55],i1[12],i2[0],i3[0])->(o0[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;
  casadi_real a60;
  a00=2.;
  a01=arg[0]? arg[0][7] : 0;
  a02=arg[0]? arg[0][8] : 0;
  a03=(a01*a02);
  a04=arg[0]? arg[0][6] : 0;
  a05=arg[0]? arg[0][9] : 0;
  a06=(a04*a05);
  a07=(a03-a06);
  a07=(a00*a07);
  a08=2.9999999999999999e-01;
  a09=arg[0]? arg[0][10] : 0;
  a10=arg[0]? arg[0][11] : 0;
  a11=(a09*a10);
  a12=2.3076923076923077e+01;
  a13=arg[0]? arg[0][39] : 0;
  a14=2.5980762113533162e-01;
  a15=1.;
  a16=casadi_sq(a02);
  a17=casadi_sq(a05);
  a18=(a16+a17);
  a18=(a00*a18);
  a18=(a15-a18);
  a19=arg[0]? arg[0][27] : 0;
  a20=(a18*a19);
  a03=(a03+a06);
  a03=(a00*a03);
  a06=arg[0]? arg[0][28] : 0;
  a21=(a03*a06);
  a20=(a20+a21);
  a21=(a01*a05);
  a22=(a04*a02);
  a23=(a21-a22);
  a23=(a00*a23);
  a24=arg[0]? arg[0][29] : 0;
  a25=(a23*a24);
  a20=(a20+a25);
  a20=(a14*a20);
  a25=-1.4999999999999994e-01;
  a26=(a07*a19);
  a27=casadi_sq(a01);
  a17=(a27+a17);
  a17=(a00*a17);
  a17=(a15-a17);
  a28=(a17*a06);
  a26=(a26+a28);
  a02=(a02*a05);
  a04=(a04*a01);
  a01=(a02+a04);
  a01=(a00*a01);
  a05=(a01*a24);
  a26=(a26+a05);
  a26=(a25*a26);
  a20=(a20-a26);
  a20=(a13*a20);
  a26=arg[0]? arg[0][25] : 0;
  a05=arg[0]? arg[0][13] : 0;
  a28=(a07*a05);
  a29=arg[0]? arg[0][14] : 0;
  a30=(a17*a29);
  a28=(a28+a30);
  a30=arg[0]? arg[0][15] : 0;
  a31=(a01*a30);
  a28=(a28+a31);
  a28=(a08*a28);
  a28=(a26*a28);
  a20=(a20-a28);
  a28=arg[0]? arg[0][53] : 0;
  a31=-2.5980762113533151e-01;
  a32=arg[0]? arg[0][41] : 0;
  a33=(a18*a32);
  a34=arg[0]? arg[0][42] : 0;
  a35=(a03*a34);
  a33=(a33+a35);
  a35=arg[0]? arg[0][43] : 0;
  a36=(a23*a35);
  a33=(a33+a36);
  a33=(a31*a33);
  a36=-1.5000000000000013e-01;
  a37=(a07*a32);
  a38=(a17*a34);
  a37=(a37+a38);
  a38=(a01*a35);
  a37=(a37+a38);
  a37=(a36*a37);
  a33=(a33-a37);
  a33=(a28*a33);
  a20=(a20+a33);
  a33=3.3333333333333333e-02;
  a33=(a33*a10);
  a37=(a09*a33);
  a38=1.6666666666666670e-02;
  a38=(a38*a09);
  a39=(a10*a38);
  a37=(a37-a39);
  a20=(a20-a37);
  a12=(a12*a20);
  a11=(a11+a12);
  a20=(a08*a11);
  a37=(a07*a20);
  a39=arg[0]? arg[0][12] : 0;
  a40=casadi_sq(a39);
  a41=casadi_sq(a10);
  a41=(a40+a41);
  a42=(a08*a41);
  a43=(a18*a42);
  a37=(a37-a43);
  a21=(a21+a22);
  a21=(a00*a21);
  a22=(a09*a39);
  a43=30.;
  a44=(a21*a05);
  a02=(a02-a04);
  a02=(a00*a02);
  a04=(a02*a29);
  a44=(a44+a04);
  a27=(a27+a16);
  a27=(a00*a27);
  a15=(a15-a27);
  a27=(a15*a30);
  a44=(a44+a27);
  a44=(a08*a44);
  a44=(a26*a44);
  a27=(a21*a19);
  a16=(a02*a06);
  a27=(a27+a16);
  a16=(a15*a24);
  a27=(a27+a16);
  a16=(a25*a27);
  a16=(a13*a16);
  a44=(a44+a16);
  a16=(a21*a32);
  a04=(a02*a34);
  a16=(a16+a04);
  a04=(a15*a35);
  a16=(a16+a04);
  a04=(a36*a16);
  a04=(a28*a04);
  a44=(a44+a04);
  a38=(a39*a38);
  a04=4.3333333333333335e-02;
  a04=(a04*a39);
  a45=(a09*a04);
  a38=(a38-a45);
  a44=(a44-a38);
  a43=(a43*a44);
  a22=(a22-a43);
  a08=(a08*a22);
  a43=(a21*a08);
  a37=(a37+a43);
  a43=(a26*a05);
  a44=(a13*a19);
  a38=(a43+a44);
  a45=(a28*a32);
  a38=(a38+a45);
  a37=(a37-a38);
  a46=1.5000000000000000e+00;
  a47=arg[0]? arg[0][20] : 0;
  a48=(a47*a30);
  a49=arg[0]? arg[0][21] : 0;
  a50=(a49*a29);
  a48=(a48-a50);
  a50=arg[0]? arg[0][17] : 0;
  a51=arg[0]? arg[0][16] : 0;
  a52=(a51*a29);
  a53=(a50*a05);
  a52=(a52-a53);
  a53=(a50*a52);
  a54=arg[0]? arg[0][18] : 0;
  a55=(a54*a05);
  a56=(a51*a30);
  a55=(a55-a56);
  a56=(a54*a55);
  a53=(a53-a56);
  a48=(a48+a53);
  a48=(a46*a48);
  a37=(a37-a48);
  a37=(a00*a37);
  a37=(a37-a43);
  a37=casadi_sq(a37);
  a43=(a17*a20);
  a48=(a03*a42);
  a43=(a43-a48);
  a48=(a02*a08);
  a43=(a43+a48);
  a48=(a26*a29);
  a53=(a13*a06);
  a56=(a48+a53);
  a57=(a28*a34);
  a56=(a56+a57);
  a43=(a43-a56);
  a49=(a49*a05);
  a58=arg[0]? arg[0][19] : 0;
  a59=(a58*a30);
  a49=(a49-a59);
  a59=(a50*a30);
  a60=(a54*a29);
  a59=(a59-a60);
  a54=(a54*a59);
  a52=(a51*a52);
  a54=(a54-a52);
  a49=(a49+a54);
  a49=(a46*a49);
  a43=(a43-a49);
  a43=(a00*a43);
  a43=(a43-a48);
  a43=casadi_sq(a43);
  a37=(a37+a43);
  a43=-9.8100000000000005e+00;
  a26=(a26*a30);
  a30=(a13*a24);
  a48=(a26+a30);
  a49=(a28*a35);
  a48=(a48+a49);
  a48=(a43-a48);
  a20=(a01*a20);
  a42=(a23*a42);
  a20=(a20-a42);
  a08=(a15*a08);
  a20=(a20+a08);
  a20=(a48+a20);
  a58=(a58*a29);
  a47=(a47*a05);
  a58=(a58-a47);
  a51=(a51*a55);
  a50=(a50*a59);
  a51=(a51-a50);
  a58=(a58+a51);
  a58=(a46*a58);
  a20=(a20-a58);
  a20=(a20-a43);
  a20=(a00*a20);
  a20=(a20-a26);
  a20=casadi_sq(a20);
  a37=(a37+a20);
  if (res[0]!=0) res[0][0]=a37;
  a37=(a10*a09);
  a37=(a37-a12);
  a12=(a14*a37);
  a20=(a25*a41);
  a12=(a12-a20);
  a20=(a18*a12);
  a26=(a25*a11);
  a09=casadi_sq(a09);
  a40=(a40+a09);
  a09=(a14*a40);
  a26=(a26-a09);
  a09=(a07*a26);
  a20=(a20+a09);
  a25=(a25*a22);
  a09=(a10*a39);
  a58=5.9999999999999986e+01;
  a10=(a10*a04);
  a39=(a39*a33);
  a10=(a10-a39);
  a27=(a14*a27);
  a13=(a13*a27);
  a16=(a31*a16);
  a28=(a28*a16);
  a13=(a13+a28);
  a10=(a10+a13);
  a58=(a58*a10);
  a09=(a09-a58);
  a14=(a14*a09);
  a25=(a25+a14);
  a14=(a21*a25);
  a20=(a20+a14);
  a20=(a20-a38);
  a14=arg[0]? arg[0][34] : 0;
  a58=(a14*a24);
  a10=arg[0]? arg[0][35] : 0;
  a13=(a10*a06);
  a58=(a58-a13);
  a13=arg[0]? arg[0][31] : 0;
  a28=arg[0]? arg[0][30] : 0;
  a16=(a28*a06);
  a27=(a13*a19);
  a16=(a16-a27);
  a27=(a13*a16);
  a39=arg[0]? arg[0][32] : 0;
  a33=(a39*a19);
  a04=(a28*a24);
  a33=(a33-a04);
  a04=(a39*a33);
  a27=(a27-a04);
  a58=(a58+a27);
  a58=(a46*a58);
  a20=(a20-a58);
  a20=(a00*a20);
  a20=(a20-a44);
  a20=casadi_sq(a20);
  a44=(a03*a12);
  a58=(a17*a26);
  a44=(a44+a58);
  a58=(a02*a25);
  a44=(a44+a58);
  a44=(a44-a56);
  a10=(a10*a19);
  a58=arg[0]? arg[0][33] : 0;
  a27=(a58*a24);
  a10=(a10-a27);
  a24=(a13*a24);
  a27=(a39*a06);
  a24=(a24-a27);
  a39=(a39*a24);
  a16=(a28*a16);
  a39=(a39-a16);
  a10=(a10+a39);
  a10=(a46*a10);
  a44=(a44-a10);
  a44=(a00*a44);
  a44=(a44-a53);
  a44=casadi_sq(a44);
  a20=(a20+a44);
  a12=(a23*a12);
  a26=(a01*a26);
  a12=(a12+a26);
  a25=(a15*a25);
  a12=(a12+a25);
  a12=(a48+a12);
  a58=(a58*a06);
  a14=(a14*a19);
  a58=(a58-a14);
  a28=(a28*a33);
  a13=(a13*a24);
  a28=(a28-a13);
  a58=(a58+a28);
  a58=(a46*a58);
  a12=(a12-a58);
  a12=(a12-a43);
  a12=(a00*a12);
  a12=(a12-a30);
  a12=casadi_sq(a12);
  a20=(a20+a12);
  if (res[0]!=0) res[0][1]=a20;
  a37=(a31*a37);
  a41=(a36*a41);
  a37=(a37-a41);
  a18=(a18*a37);
  a11=(a36*a11);
  a40=(a31*a40);
  a11=(a11-a40);
  a07=(a07*a11);
  a18=(a18+a07);
  a36=(a36*a22);
  a31=(a31*a09);
  a36=(a36+a31);
  a21=(a21*a36);
  a18=(a18+a21);
  a18=(a18-a38);
  a38=arg[0]? arg[0][48] : 0;
  a21=(a38*a35);
  a31=arg[0]? arg[0][49] : 0;
  a09=(a31*a34);
  a21=(a21-a09);
  a09=arg[0]? arg[0][45] : 0;
  a22=arg[0]? arg[0][44] : 0;
  a07=(a22*a34);
  a40=(a09*a32);
  a07=(a07-a40);
  a40=(a09*a07);
  a41=arg[0]? arg[0][46] : 0;
  a20=(a41*a32);
  a12=(a22*a35);
  a20=(a20-a12);
  a12=(a41*a20);
  a40=(a40-a12);
  a21=(a21+a40);
  a21=(a46*a21);
  a18=(a18-a21);
  a18=(a00*a18);
  a18=(a18-a45);
  a18=casadi_sq(a18);
  a03=(a03*a37);
  a17=(a17*a11);
  a03=(a03+a17);
  a02=(a02*a36);
  a03=(a03+a02);
  a03=(a03-a56);
  a31=(a31*a32);
  a56=arg[0]? arg[0][47] : 0;
  a02=(a56*a35);
  a31=(a31-a02);
  a35=(a09*a35);
  a02=(a41*a34);
  a35=(a35-a02);
  a41=(a41*a35);
  a07=(a22*a07);
  a41=(a41-a07);
  a31=(a31+a41);
  a31=(a46*a31);
  a03=(a03-a31);
  a03=(a00*a03);
  a03=(a03-a57);
  a03=casadi_sq(a03);
  a18=(a18+a03);
  a23=(a23*a37);
  a01=(a01*a11);
  a23=(a23+a01);
  a15=(a15*a36);
  a23=(a23+a15);
  a48=(a48+a23);
  a56=(a56*a34);
  a38=(a38*a32);
  a56=(a56-a38);
  a22=(a22*a20);
  a09=(a09*a35);
  a22=(a22-a09);
  a56=(a56+a22);
  a46=(a46*a56);
  a48=(a48-a46);
  a48=(a48-a43);
  a00=(a00*a48);
  a00=(a00-a49);
  a00=casadi_sq(a00);
  a18=(a18+a00);
  if (res[0]!=0) res[0][2]=a18;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_3cables_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_3cables_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_3cables_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinodynamic_load_3cables_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_3cables_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinodynamic_load_3cables_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void kinodynamic_load_3cables_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void kinodynamic_load_3cables_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int kinodynamic_load_3cables_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int kinodynamic_load_3cables_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real kinodynamic_load_3cables_constr_h_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinodynamic_load_3cables_constr_h_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinodynamic_load_3cables_constr_h_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinodynamic_load_3cables_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinodynamic_load_3cables_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_3cables_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_3cables_constr_h_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
