/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) kinodynamic_load_3cables_cost_y_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {55, 1, 1};
static const casadi_int casadi_s1[3] = {12, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {73, 1, 1};

/* kinodynamic_load_3cables_cost_y_fun:(i0[55],i1[12],i2[0],i3[],i4[0])->(o0[73]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  a00=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a01=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][1]=a01;
  a02=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][2]=a02;
  a02=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][3]=a02;
  a02=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][4]=a02;
  a02=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][5]=a02;
  a02=arg[0]? arg[0][6] : 0;
  if (res[0]!=0) res[0][6]=a02;
  a03=arg[0]? arg[0][7] : 0;
  if (res[0]!=0) res[0][7]=a03;
  a04=arg[0]? arg[0][8] : 0;
  if (res[0]!=0) res[0][8]=a04;
  a05=arg[0]? arg[0][9] : 0;
  if (res[0]!=0) res[0][9]=a05;
  a06=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][10]=a06;
  a06=arg[0]? arg[0][11] : 0;
  if (res[0]!=0) res[0][11]=a06;
  a06=arg[0]? arg[0][12] : 0;
  if (res[0]!=0) res[0][12]=a06;
  a06=arg[0]? arg[0][13] : 0;
  if (res[0]!=0) res[0][13]=a06;
  a07=arg[0]? arg[0][14] : 0;
  if (res[0]!=0) res[0][14]=a07;
  a08=arg[0]? arg[0][15] : 0;
  if (res[0]!=0) res[0][15]=a08;
  a08=arg[0]? arg[0][16] : 0;
  if (res[0]!=0) res[0][16]=a08;
  a08=arg[0]? arg[0][17] : 0;
  if (res[0]!=0) res[0][17]=a08;
  a08=arg[0]? arg[0][18] : 0;
  if (res[0]!=0) res[0][18]=a08;
  a08=arg[0]? arg[0][19] : 0;
  if (res[0]!=0) res[0][19]=a08;
  a08=arg[0]? arg[0][20] : 0;
  if (res[0]!=0) res[0][20]=a08;
  a08=arg[0]? arg[0][21] : 0;
  if (res[0]!=0) res[0][21]=a08;
  a08=arg[0]? arg[0][22] : 0;
  if (res[0]!=0) res[0][22]=a08;
  a08=arg[0]? arg[0][23] : 0;
  if (res[0]!=0) res[0][23]=a08;
  a08=arg[0]? arg[0][24] : 0;
  if (res[0]!=0) res[0][24]=a08;
  a08=arg[0]? arg[0][25] : 0;
  if (res[0]!=0) res[0][25]=a08;
  a08=arg[0]? arg[0][26] : 0;
  if (res[0]!=0) res[0][26]=a08;
  a08=arg[0]? arg[0][27] : 0;
  if (res[0]!=0) res[0][27]=a08;
  a09=arg[0]? arg[0][28] : 0;
  if (res[0]!=0) res[0][28]=a09;
  a10=arg[0]? arg[0][29] : 0;
  if (res[0]!=0) res[0][29]=a10;
  a10=arg[0]? arg[0][30] : 0;
  if (res[0]!=0) res[0][30]=a10;
  a10=arg[0]? arg[0][31] : 0;
  if (res[0]!=0) res[0][31]=a10;
  a10=arg[0]? arg[0][32] : 0;
  if (res[0]!=0) res[0][32]=a10;
  a10=arg[0]? arg[0][33] : 0;
  if (res[0]!=0) res[0][33]=a10;
  a10=arg[0]? arg[0][34] : 0;
  if (res[0]!=0) res[0][34]=a10;
  a10=arg[0]? arg[0][35] : 0;
  if (res[0]!=0) res[0][35]=a10;
  a10=arg[0]? arg[0][36] : 0;
  if (res[0]!=0) res[0][36]=a10;
  a10=arg[0]? arg[0][37] : 0;
  if (res[0]!=0) res[0][37]=a10;
  a10=arg[0]? arg[0][38] : 0;
  if (res[0]!=0) res[0][38]=a10;
  a10=arg[0]? arg[0][39] : 0;
  if (res[0]!=0) res[0][39]=a10;
  a10=arg[0]? arg[0][40] : 0;
  if (res[0]!=0) res[0][40]=a10;
  a10=arg[0]? arg[0][41] : 0;
  if (res[0]!=0) res[0][41]=a10;
  a11=arg[0]? arg[0][42] : 0;
  if (res[0]!=0) res[0][42]=a11;
  a12=arg[0]? arg[0][43] : 0;
  if (res[0]!=0) res[0][43]=a12;
  a12=arg[0]? arg[0][44] : 0;
  if (res[0]!=0) res[0][44]=a12;
  a12=arg[0]? arg[0][45] : 0;
  if (res[0]!=0) res[0][45]=a12;
  a12=arg[0]? arg[0][46] : 0;
  if (res[0]!=0) res[0][46]=a12;
  a12=arg[0]? arg[0][47] : 0;
  if (res[0]!=0) res[0][47]=a12;
  a12=arg[0]? arg[0][48] : 0;
  if (res[0]!=0) res[0][48]=a12;
  a12=arg[0]? arg[0][49] : 0;
  if (res[0]!=0) res[0][49]=a12;
  a12=arg[0]? arg[0][50] : 0;
  if (res[0]!=0) res[0][50]=a12;
  a12=arg[0]? arg[0][51] : 0;
  if (res[0]!=0) res[0][51]=a12;
  a12=arg[0]? arg[0][52] : 0;
  if (res[0]!=0) res[0][52]=a12;
  a12=arg[0]? arg[0][53] : 0;
  if (res[0]!=0) res[0][53]=a12;
  a12=arg[0]? arg[0][54] : 0;
  if (res[0]!=0) res[0][54]=a12;
  a12=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][55]=a12;
  a12=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][56]=a12;
  a12=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][57]=a12;
  a12=arg[1]? arg[1][3] : 0;
  if (res[0]!=0) res[0][58]=a12;
  a12=arg[1]? arg[1][4] : 0;
  if (res[0]!=0) res[0][59]=a12;
  a12=arg[1]? arg[1][5] : 0;
  if (res[0]!=0) res[0][60]=a12;
  a12=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][61]=a12;
  a12=arg[1]? arg[1][7] : 0;
  if (res[0]!=0) res[0][62]=a12;
  a12=arg[1]? arg[1][8] : 0;
  if (res[0]!=0) res[0][63]=a12;
  a12=arg[1]? arg[1][9] : 0;
  if (res[0]!=0) res[0][64]=a12;
  a12=arg[1]? arg[1][10] : 0;
  if (res[0]!=0) res[0][65]=a12;
  a12=arg[1]? arg[1][11] : 0;
  if (res[0]!=0) res[0][66]=a12;
  a12=1.;
  a13=10.;
  a14=8.0999999999999983e-01;
  a15=2.9999999999999999e-01;
  a16=2.;
  a17=casadi_sq(a04);
  a18=casadi_sq(a05);
  a17=(a17+a18);
  a17=(a16*a17);
  a17=(a12-a17);
  a19=(a15*a17);
  a19=(a00+a19);
  a20=2.5000000000000000e+00;
  a21=(a19-a20);
  a21=casadi_sq(a21);
  a04=(a03*a04);
  a02=(a02*a05);
  a05=(a04+a02);
  a05=(a16*a05);
  a15=(a15*a05);
  a15=(a01+a15);
  a22=1.0000000000000000e-02;
  a23=(a15-a22);
  a23=casadi_sq(a23);
  a21=(a21+a23);
  a21=(a14-a21);
  a21=(a13*a21);
  a21=exp(a21);
  a21=(a12+a21);
  a21=log(a21);
  if (res[0]!=0) res[0][67]=a21;
  a21=1.5000000000000000e+00;
  a06=(a21*a06);
  a19=(a19-a06);
  a19=(a19-a20);
  a19=casadi_sq(a19);
  a07=(a21*a07);
  a15=(a15-a07);
  a15=(a15-a22);
  a15=casadi_sq(a15);
  a19=(a19+a15);
  a19=(a14-a19);
  a19=(a13*a19);
  a19=exp(a19);
  a19=(a12+a19);
  a19=log(a19);
  if (res[0]!=0) res[0][68]=a19;
  a19=-1.4999999999999994e-01;
  a15=(a19*a17);
  a07=2.5980762113533162e-01;
  a04=(a04-a02);
  a04=(a16*a04);
  a02=(a07*a04);
  a15=(a15+a02);
  a15=(a00+a15);
  a02=(a15-a20);
  a02=casadi_sq(a02);
  a19=(a19*a05);
  a03=casadi_sq(a03);
  a03=(a03+a18);
  a16=(a16*a03);
  a16=(a12-a16);
  a07=(a07*a16);
  a19=(a19+a07);
  a19=(a01+a19);
  a07=(a19-a22);
  a07=casadi_sq(a07);
  a02=(a02+a07);
  a02=(a14-a02);
  a02=(a13*a02);
  a02=exp(a02);
  a02=(a12+a02);
  a02=log(a02);
  if (res[0]!=0) res[0][69]=a02;
  a08=(a21*a08);
  a15=(a15-a08);
  a15=(a15-a20);
  a15=casadi_sq(a15);
  a09=(a21*a09);
  a19=(a19-a09);
  a19=(a19-a22);
  a19=casadi_sq(a19);
  a15=(a15+a19);
  a15=(a14-a15);
  a15=(a13*a15);
  a15=exp(a15);
  a15=(a12+a15);
  a15=log(a15);
  if (res[0]!=0) res[0][70]=a15;
  a15=-1.5000000000000013e-01;
  a17=(a15*a17);
  a19=-2.5980762113533151e-01;
  a04=(a19*a04);
  a17=(a17+a04);
  a00=(a00+a17);
  a17=(a00-a20);
  a17=casadi_sq(a17);
  a15=(a15*a05);
  a19=(a19*a16);
  a15=(a15+a19);
  a01=(a01+a15);
  a15=(a01-a22);
  a15=casadi_sq(a15);
  a17=(a17+a15);
  a17=(a14-a17);
  a17=(a13*a17);
  a17=exp(a17);
  a17=(a12+a17);
  a17=log(a17);
  if (res[0]!=0) res[0][71]=a17;
  a10=(a21*a10);
  a00=(a00-a10);
  a00=(a00-a20);
  a00=casadi_sq(a00);
  a21=(a21*a11);
  a01=(a01-a21);
  a01=(a01-a22);
  a01=casadi_sq(a01);
  a00=(a00+a01);
  a14=(a14-a00);
  a13=(a13*a14);
  a13=exp(a13);
  a12=(a12+a13);
  a12=log(a12);
  if (res[0]!=0) res[0][72]=a12;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_3cables_cost_y_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_3cables_cost_y_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_3cables_cost_y_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinodynamic_load_3cables_cost_y_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_3cables_cost_y_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinodynamic_load_3cables_cost_y_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void kinodynamic_load_3cables_cost_y_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void kinodynamic_load_3cables_cost_y_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int kinodynamic_load_3cables_cost_y_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int kinodynamic_load_3cables_cost_y_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real kinodynamic_load_3cables_cost_y_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinodynamic_load_3cables_cost_y_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinodynamic_load_3cables_cost_y_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinodynamic_load_3cables_cost_y_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinodynamic_load_3cables_cost_y_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_3cables_cost_y_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_3cables_cost_y_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
