/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) kinodynamic_load_3cables_cost_y_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {55, 1, 1};
static const casadi_int casadi_s1[3] = {12, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {73, 1, 1};
static const casadi_int casadi_s5[185] = 
  {67, 73, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  14, 15, 16, 17, 18, 19, 20, 21,
  22, 23, 24, 25, 26, 27, 28, 29,
  30, 31, 32, 33, 34, 35, 36, 37,
  38, 39, 40, 41, 42, 43, 44, 45,
  46, 47, 48, 49, 50, 51, 52, 53,
  54, 55, 56, 57, 58, 59, 60, 61,
  62, 63, 64, 65, 66, 67, 73, 81,
  87, 95, 101, 109, 12, 13, 14, 15,
  16, 17, 18, 19, 20, 21, 22, 23,
  24, 25, 26, 27, 28, 29, 30, 31,
  32, 33, 34, 35, 36, 37, 38, 39,
  40, 41, 42, 43, 44, 45, 46, 47,
  48, 49, 50, 51, 52, 53, 54, 55,
  56, 57, 58, 59, 60, 61, 62, 63,
  64, 65, 66, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 12,
  13, 18, 19, 20, 21, 12, 13, 18,
  19, 20, 21, 25, 26, 12, 13, 18,
  19, 20, 21, 12, 13, 18, 19, 20,
  21, 39, 40, 12, 13, 18, 19, 20,
  21, 12, 13, 18, 19, 20, 21, 53,
  54};
static const casadi_int casadi_s6[3] = {73, 0, 1};

/* kinodynamic_load_3cables_cost_y_fun_jac_ut_xt:(i0[55],i1[12],i2[0],i3[],i4[0])->(o0[73],o1[67x73,109nz],o2[73x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43;
  a00=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a01=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][1]=a01;
  a02=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][2]=a02;
  a02=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][3]=a02;
  a02=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][4]=a02;
  a02=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][5]=a02;
  a02=arg[0]? arg[0][6] : 0;
  if (res[0]!=0) res[0][6]=a02;
  a03=arg[0]? arg[0][7] : 0;
  if (res[0]!=0) res[0][7]=a03;
  a04=arg[0]? arg[0][8] : 0;
  if (res[0]!=0) res[0][8]=a04;
  a05=arg[0]? arg[0][9] : 0;
  if (res[0]!=0) res[0][9]=a05;
  a06=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][10]=a06;
  a06=arg[0]? arg[0][11] : 0;
  if (res[0]!=0) res[0][11]=a06;
  a06=arg[0]? arg[0][12] : 0;
  if (res[0]!=0) res[0][12]=a06;
  a06=arg[0]? arg[0][13] : 0;
  if (res[0]!=0) res[0][13]=a06;
  a07=arg[0]? arg[0][14] : 0;
  if (res[0]!=0) res[0][14]=a07;
  a08=arg[0]? arg[0][15] : 0;
  if (res[0]!=0) res[0][15]=a08;
  a08=arg[0]? arg[0][16] : 0;
  if (res[0]!=0) res[0][16]=a08;
  a08=arg[0]? arg[0][17] : 0;
  if (res[0]!=0) res[0][17]=a08;
  a08=arg[0]? arg[0][18] : 0;
  if (res[0]!=0) res[0][18]=a08;
  a08=arg[0]? arg[0][19] : 0;
  if (res[0]!=0) res[0][19]=a08;
  a08=arg[0]? arg[0][20] : 0;
  if (res[0]!=0) res[0][20]=a08;
  a08=arg[0]? arg[0][21] : 0;
  if (res[0]!=0) res[0][21]=a08;
  a08=arg[0]? arg[0][22] : 0;
  if (res[0]!=0) res[0][22]=a08;
  a08=arg[0]? arg[0][23] : 0;
  if (res[0]!=0) res[0][23]=a08;
  a08=arg[0]? arg[0][24] : 0;
  if (res[0]!=0) res[0][24]=a08;
  a08=arg[0]? arg[0][25] : 0;
  if (res[0]!=0) res[0][25]=a08;
  a08=arg[0]? arg[0][26] : 0;
  if (res[0]!=0) res[0][26]=a08;
  a08=arg[0]? arg[0][27] : 0;
  if (res[0]!=0) res[0][27]=a08;
  a09=arg[0]? arg[0][28] : 0;
  if (res[0]!=0) res[0][28]=a09;
  a10=arg[0]? arg[0][29] : 0;
  if (res[0]!=0) res[0][29]=a10;
  a10=arg[0]? arg[0][30] : 0;
  if (res[0]!=0) res[0][30]=a10;
  a10=arg[0]? arg[0][31] : 0;
  if (res[0]!=0) res[0][31]=a10;
  a10=arg[0]? arg[0][32] : 0;
  if (res[0]!=0) res[0][32]=a10;
  a10=arg[0]? arg[0][33] : 0;
  if (res[0]!=0) res[0][33]=a10;
  a10=arg[0]? arg[0][34] : 0;
  if (res[0]!=0) res[0][34]=a10;
  a10=arg[0]? arg[0][35] : 0;
  if (res[0]!=0) res[0][35]=a10;
  a10=arg[0]? arg[0][36] : 0;
  if (res[0]!=0) res[0][36]=a10;
  a10=arg[0]? arg[0][37] : 0;
  if (res[0]!=0) res[0][37]=a10;
  a10=arg[0]? arg[0][38] : 0;
  if (res[0]!=0) res[0][38]=a10;
  a10=arg[0]? arg[0][39] : 0;
  if (res[0]!=0) res[0][39]=a10;
  a10=arg[0]? arg[0][40] : 0;
  if (res[0]!=0) res[0][40]=a10;
  a10=arg[0]? arg[0][41] : 0;
  if (res[0]!=0) res[0][41]=a10;
  a11=arg[0]? arg[0][42] : 0;
  if (res[0]!=0) res[0][42]=a11;
  a12=arg[0]? arg[0][43] : 0;
  if (res[0]!=0) res[0][43]=a12;
  a12=arg[0]? arg[0][44] : 0;
  if (res[0]!=0) res[0][44]=a12;
  a12=arg[0]? arg[0][45] : 0;
  if (res[0]!=0) res[0][45]=a12;
  a12=arg[0]? arg[0][46] : 0;
  if (res[0]!=0) res[0][46]=a12;
  a12=arg[0]? arg[0][47] : 0;
  if (res[0]!=0) res[0][47]=a12;
  a12=arg[0]? arg[0][48] : 0;
  if (res[0]!=0) res[0][48]=a12;
  a12=arg[0]? arg[0][49] : 0;
  if (res[0]!=0) res[0][49]=a12;
  a12=arg[0]? arg[0][50] : 0;
  if (res[0]!=0) res[0][50]=a12;
  a12=arg[0]? arg[0][51] : 0;
  if (res[0]!=0) res[0][51]=a12;
  a12=arg[0]? arg[0][52] : 0;
  if (res[0]!=0) res[0][52]=a12;
  a12=arg[0]? arg[0][53] : 0;
  if (res[0]!=0) res[0][53]=a12;
  a12=arg[0]? arg[0][54] : 0;
  if (res[0]!=0) res[0][54]=a12;
  a12=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][55]=a12;
  a12=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][56]=a12;
  a12=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][57]=a12;
  a12=arg[1]? arg[1][3] : 0;
  if (res[0]!=0) res[0][58]=a12;
  a12=arg[1]? arg[1][4] : 0;
  if (res[0]!=0) res[0][59]=a12;
  a12=arg[1]? arg[1][5] : 0;
  if (res[0]!=0) res[0][60]=a12;
  a12=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][61]=a12;
  a12=arg[1]? arg[1][7] : 0;
  if (res[0]!=0) res[0][62]=a12;
  a12=arg[1]? arg[1][8] : 0;
  if (res[0]!=0) res[0][63]=a12;
  a12=arg[1]? arg[1][9] : 0;
  if (res[0]!=0) res[0][64]=a12;
  a12=arg[1]? arg[1][10] : 0;
  if (res[0]!=0) res[0][65]=a12;
  a12=arg[1]? arg[1][11] : 0;
  if (res[0]!=0) res[0][66]=a12;
  a12=1.;
  a13=10.;
  a14=8.0999999999999983e-01;
  a15=2.9999999999999999e-01;
  a16=2.;
  a17=casadi_sq(a04);
  a18=casadi_sq(a05);
  a17=(a17+a18);
  a17=(a16*a17);
  a17=(a12-a17);
  a19=(a15*a17);
  a19=(a00+a19);
  a20=2.5000000000000000e+00;
  a21=(a19-a20);
  a22=casadi_sq(a21);
  a23=(a03*a04);
  a24=(a02*a05);
  a25=(a23+a24);
  a25=(a16*a25);
  a26=(a15*a25);
  a26=(a01+a26);
  a27=1.0000000000000000e-02;
  a28=(a26-a27);
  a29=casadi_sq(a28);
  a22=(a22+a29);
  a22=(a14-a22);
  a22=(a13*a22);
  a22=exp(a22);
  a29=(a12+a22);
  a30=log(a29);
  if (res[0]!=0) res[0][67]=a30;
  a30=1.5000000000000000e+00;
  a06=(a30*a06);
  a19=(a19-a06);
  a19=(a19-a20);
  a06=casadi_sq(a19);
  a07=(a30*a07);
  a26=(a26-a07);
  a26=(a26-a27);
  a07=casadi_sq(a26);
  a06=(a06+a07);
  a06=(a14-a06);
  a06=(a13*a06);
  a06=exp(a06);
  a07=(a12+a06);
  a31=log(a07);
  if (res[0]!=0) res[0][68]=a31;
  a31=-1.4999999999999994e-01;
  a32=(a31*a17);
  a33=2.5980762113533162e-01;
  a23=(a23-a24);
  a23=(a16*a23);
  a24=(a33*a23);
  a32=(a32+a24);
  a32=(a00+a32);
  a24=(a32-a20);
  a34=casadi_sq(a24);
  a35=(a31*a25);
  a36=casadi_sq(a03);
  a36=(a36+a18);
  a36=(a16*a36);
  a36=(a12-a36);
  a18=(a33*a36);
  a35=(a35+a18);
  a35=(a01+a35);
  a18=(a35-a27);
  a37=casadi_sq(a18);
  a34=(a34+a37);
  a34=(a14-a34);
  a34=(a13*a34);
  a34=exp(a34);
  a37=(a12+a34);
  a38=log(a37);
  if (res[0]!=0) res[0][69]=a38;
  a08=(a30*a08);
  a32=(a32-a08);
  a32=(a32-a20);
  a08=casadi_sq(a32);
  a09=(a30*a09);
  a35=(a35-a09);
  a35=(a35-a27);
  a09=casadi_sq(a35);
  a08=(a08+a09);
  a08=(a14-a08);
  a08=(a13*a08);
  a08=exp(a08);
  a09=(a12+a08);
  a38=log(a09);
  if (res[0]!=0) res[0][70]=a38;
  a38=-1.5000000000000013e-01;
  a17=(a38*a17);
  a39=-2.5980762113533151e-01;
  a23=(a39*a23);
  a17=(a17+a23);
  a00=(a00+a17);
  a17=(a00-a20);
  a23=casadi_sq(a17);
  a25=(a38*a25);
  a36=(a39*a36);
  a25=(a25+a36);
  a01=(a01+a25);
  a25=(a01-a27);
  a36=casadi_sq(a25);
  a23=(a23+a36);
  a23=(a14-a23);
  a23=(a13*a23);
  a23=exp(a23);
  a36=(a12+a23);
  a40=log(a36);
  if (res[0]!=0) res[0][71]=a40;
  a10=(a30*a10);
  a00=(a00-a10);
  a00=(a00-a20);
  a20=casadi_sq(a00);
  a30=(a30*a11);
  a01=(a01-a30);
  a01=(a01-a27);
  a27=casadi_sq(a01);
  a20=(a20+a27);
  a14=(a14-a20);
  a14=(a13*a14);
  a14=exp(a14);
  a20=(a12+a14);
  a27=log(a20);
  if (res[0]!=0) res[0][72]=a27;
  if (res[1]!=0) res[1][0]=a12;
  if (res[1]!=0) res[1][1]=a12;
  if (res[1]!=0) res[1][2]=a12;
  if (res[1]!=0) res[1][3]=a12;
  if (res[1]!=0) res[1][4]=a12;
  if (res[1]!=0) res[1][5]=a12;
  if (res[1]!=0) res[1][6]=a12;
  if (res[1]!=0) res[1][7]=a12;
  if (res[1]!=0) res[1][8]=a12;
  if (res[1]!=0) res[1][9]=a12;
  if (res[1]!=0) res[1][10]=a12;
  if (res[1]!=0) res[1][11]=a12;
  if (res[1]!=0) res[1][12]=a12;
  if (res[1]!=0) res[1][13]=a12;
  if (res[1]!=0) res[1][14]=a12;
  if (res[1]!=0) res[1][15]=a12;
  if (res[1]!=0) res[1][16]=a12;
  if (res[1]!=0) res[1][17]=a12;
  if (res[1]!=0) res[1][18]=a12;
  if (res[1]!=0) res[1][19]=a12;
  if (res[1]!=0) res[1][20]=a12;
  if (res[1]!=0) res[1][21]=a12;
  if (res[1]!=0) res[1][22]=a12;
  if (res[1]!=0) res[1][23]=a12;
  if (res[1]!=0) res[1][24]=a12;
  if (res[1]!=0) res[1][25]=a12;
  if (res[1]!=0) res[1][26]=a12;
  if (res[1]!=0) res[1][27]=a12;
  if (res[1]!=0) res[1][28]=a12;
  if (res[1]!=0) res[1][29]=a12;
  if (res[1]!=0) res[1][30]=a12;
  if (res[1]!=0) res[1][31]=a12;
  if (res[1]!=0) res[1][32]=a12;
  if (res[1]!=0) res[1][33]=a12;
  if (res[1]!=0) res[1][34]=a12;
  if (res[1]!=0) res[1][35]=a12;
  if (res[1]!=0) res[1][36]=a12;
  if (res[1]!=0) res[1][37]=a12;
  if (res[1]!=0) res[1][38]=a12;
  if (res[1]!=0) res[1][39]=a12;
  if (res[1]!=0) res[1][40]=a12;
  if (res[1]!=0) res[1][41]=a12;
  if (res[1]!=0) res[1][42]=a12;
  if (res[1]!=0) res[1][43]=a12;
  if (res[1]!=0) res[1][44]=a12;
  if (res[1]!=0) res[1][45]=a12;
  if (res[1]!=0) res[1][46]=a12;
  if (res[1]!=0) res[1][47]=a12;
  if (res[1]!=0) res[1][48]=a12;
  if (res[1]!=0) res[1][49]=a12;
  if (res[1]!=0) res[1][50]=a12;
  if (res[1]!=0) res[1][51]=a12;
  if (res[1]!=0) res[1][52]=a12;
  if (res[1]!=0) res[1][53]=a12;
  if (res[1]!=0) res[1][54]=a12;
  if (res[1]!=0) res[1][55]=a12;
  if (res[1]!=0) res[1][56]=a12;
  if (res[1]!=0) res[1][57]=a12;
  if (res[1]!=0) res[1][58]=a12;
  if (res[1]!=0) res[1][59]=a12;
  if (res[1]!=0) res[1][60]=a12;
  if (res[1]!=0) res[1][61]=a12;
  if (res[1]!=0) res[1][62]=a12;
  if (res[1]!=0) res[1][63]=a12;
  if (res[1]!=0) res[1][64]=a12;
  if (res[1]!=0) res[1][65]=a12;
  if (res[1]!=0) res[1][66]=a12;
  a21=(a21+a21);
  a12=(a13*a21);
  a12=(a22*a12);
  a12=(a12/a29);
  a12=(-a12);
  if (res[1]!=0) res[1][67]=a12;
  a28=(a28+a28);
  a12=(a13*a28);
  a12=(a22*a12);
  a12=(a12/a29);
  a12=(-a12);
  if (res[1]!=0) res[1][68]=a12;
  a12=(a16*a05);
  a27=(a15*a12);
  a30=(a28*a27);
  a30=(a13*a30);
  a30=(a22*a30);
  a30=(a30/a29);
  a30=(-a30);
  if (res[1]!=0) res[1][69]=a30;
  a30=(a16*a04);
  a11=(a15*a30);
  a10=(a28*a11);
  a10=(a13*a10);
  a10=(a22*a10);
  a10=(a10/a29);
  a10=(-a10);
  if (res[1]!=0) res[1][70]=a10;
  a10=(a16*a03);
  a40=(a15*a10);
  a41=(a28*a40);
  a04=(a04+a04);
  a04=(a16*a04);
  a42=(a15*a04);
  a43=(a21*a42);
  a41=(a41-a43);
  a41=(a13*a41);
  a41=(a22*a41);
  a41=(a41/a29);
  a41=(-a41);
  if (res[1]!=0) res[1][71]=a41;
  a02=(a16*a02);
  a41=(a15*a02);
  a28=(a28*a41);
  a05=(a05+a05);
  a05=(a16*a05);
  a15=(a15*a05);
  a21=(a21*a15);
  a28=(a28-a21);
  a28=(a13*a28);
  a22=(a22*a28);
  a22=(a22/a29);
  a22=(-a22);
  if (res[1]!=0) res[1][72]=a22;
  a19=(a19+a19);
  a22=(a13*a19);
  a22=(a06*a22);
  a22=(a22/a07);
  a22=(-a22);
  if (res[1]!=0) res[1][73]=a22;
  a26=(a26+a26);
  a22=(a13*a26);
  a22=(a06*a22);
  a22=(a22/a07);
  a22=(-a22);
  if (res[1]!=0) res[1][74]=a22;
  a27=(a26*a27);
  a27=(a13*a27);
  a27=(a06*a27);
  a27=(a27/a07);
  a27=(-a27);
  if (res[1]!=0) res[1][75]=a27;
  a11=(a26*a11);
  a11=(a13*a11);
  a11=(a06*a11);
  a11=(a11/a07);
  a11=(-a11);
  if (res[1]!=0) res[1][76]=a11;
  a40=(a26*a40);
  a42=(a19*a42);
  a40=(a40-a42);
  a40=(a13*a40);
  a40=(a06*a40);
  a40=(a40/a07);
  a40=(-a40);
  if (res[1]!=0) res[1][77]=a40;
  a41=(a26*a41);
  a15=(a19*a15);
  a41=(a41-a15);
  a41=(a13*a41);
  a41=(a06*a41);
  a41=(a41/a07);
  a41=(-a41);
  if (res[1]!=0) res[1][78]=a41;
  a41=-1.5000000000000000e+00;
  a19=(a41*a19);
  a19=(a13*a19);
  a19=(a06*a19);
  a19=(a19/a07);
  a19=(-a19);
  if (res[1]!=0) res[1][79]=a19;
  a26=(a41*a26);
  a26=(a13*a26);
  a06=(a06*a26);
  a06=(a06/a07);
  a06=(-a06);
  if (res[1]!=0) res[1][80]=a06;
  a24=(a24+a24);
  a06=(a13*a24);
  a06=(a34*a06);
  a06=(a06/a37);
  a06=(-a06);
  if (res[1]!=0) res[1][81]=a06;
  a18=(a18+a18);
  a06=(a13*a18);
  a06=(a34*a06);
  a06=(a06/a37);
  a06=(-a06);
  if (res[1]!=0) res[1][82]=a06;
  a06=(a31*a12);
  a07=(a18*a06);
  a26=(a33*a12);
  a19=(a24*a26);
  a07=(a07-a19);
  a07=(a13*a07);
  a07=(a34*a07);
  a07=(a07/a37);
  a07=(-a07);
  if (res[1]!=0) res[1][83]=a07;
  a07=(a33*a30);
  a19=(a24*a07);
  a15=(a31*a30);
  a03=(a03+a03);
  a16=(a16*a03);
  a03=(a33*a16);
  a15=(a15-a03);
  a03=(a18*a15);
  a19=(a19+a03);
  a19=(a13*a19);
  a19=(a34*a19);
  a19=(a19/a37);
  a19=(-a19);
  if (res[1]!=0) res[1][84]=a19;
  a19=(a33*a10);
  a03=(a31*a04);
  a19=(a19-a03);
  a03=(a24*a19);
  a40=(a31*a10);
  a42=(a18*a40);
  a03=(a03+a42);
  a03=(a13*a03);
  a03=(a34*a03);
  a03=(a03/a37);
  a03=(-a03);
  if (res[1]!=0) res[1][85]=a03;
  a03=(a31*a02);
  a42=(a33*a05);
  a03=(a03-a42);
  a18=(a18*a03);
  a31=(a31*a05);
  a33=(a33*a02);
  a31=(a31+a33);
  a24=(a24*a31);
  a18=(a18-a24);
  a18=(a13*a18);
  a34=(a34*a18);
  a34=(a34/a37);
  a34=(-a34);
  if (res[1]!=0) res[1][86]=a34;
  a32=(a32+a32);
  a34=(a13*a32);
  a34=(a08*a34);
  a34=(a34/a09);
  a34=(-a34);
  if (res[1]!=0) res[1][87]=a34;
  a35=(a35+a35);
  a34=(a13*a35);
  a34=(a08*a34);
  a34=(a34/a09);
  a34=(-a34);
  if (res[1]!=0) res[1][88]=a34;
  a06=(a35*a06);
  a26=(a32*a26);
  a06=(a06-a26);
  a06=(a13*a06);
  a06=(a08*a06);
  a06=(a06/a09);
  a06=(-a06);
  if (res[1]!=0) res[1][89]=a06;
  a07=(a32*a07);
  a15=(a35*a15);
  a07=(a07+a15);
  a07=(a13*a07);
  a07=(a08*a07);
  a07=(a07/a09);
  a07=(-a07);
  if (res[1]!=0) res[1][90]=a07;
  a19=(a32*a19);
  a40=(a35*a40);
  a19=(a19+a40);
  a19=(a13*a19);
  a19=(a08*a19);
  a19=(a19/a09);
  a19=(-a19);
  if (res[1]!=0) res[1][91]=a19;
  a03=(a35*a03);
  a31=(a32*a31);
  a03=(a03-a31);
  a03=(a13*a03);
  a03=(a08*a03);
  a03=(a03/a09);
  a03=(-a03);
  if (res[1]!=0) res[1][92]=a03;
  a32=(a41*a32);
  a32=(a13*a32);
  a32=(a08*a32);
  a32=(a32/a09);
  a32=(-a32);
  if (res[1]!=0) res[1][93]=a32;
  a35=(a41*a35);
  a35=(a13*a35);
  a08=(a08*a35);
  a08=(a08/a09);
  a08=(-a08);
  if (res[1]!=0) res[1][94]=a08;
  a17=(a17+a17);
  a08=(a13*a17);
  a08=(a23*a08);
  a08=(a08/a36);
  a08=(-a08);
  if (res[1]!=0) res[1][95]=a08;
  a25=(a25+a25);
  a08=(a13*a25);
  a08=(a23*a08);
  a08=(a08/a36);
  a08=(-a08);
  if (res[1]!=0) res[1][96]=a08;
  a08=(a38*a12);
  a09=(a25*a08);
  a12=(a39*a12);
  a35=(a17*a12);
  a09=(a09-a35);
  a09=(a13*a09);
  a09=(a23*a09);
  a09=(a09/a36);
  a09=(-a09);
  if (res[1]!=0) res[1][97]=a09;
  a09=(a39*a30);
  a35=(a17*a09);
  a30=(a38*a30);
  a16=(a39*a16);
  a30=(a30-a16);
  a16=(a25*a30);
  a35=(a35+a16);
  a35=(a13*a35);
  a35=(a23*a35);
  a35=(a35/a36);
  a35=(-a35);
  if (res[1]!=0) res[1][98]=a35;
  a35=(a39*a10);
  a04=(a38*a04);
  a35=(a35-a04);
  a04=(a17*a35);
  a10=(a38*a10);
  a16=(a25*a10);
  a04=(a04+a16);
  a04=(a13*a04);
  a04=(a23*a04);
  a04=(a04/a36);
  a04=(-a04);
  if (res[1]!=0) res[1][99]=a04;
  a04=(a38*a02);
  a16=(a39*a05);
  a04=(a04-a16);
  a25=(a25*a04);
  a38=(a38*a05);
  a39=(a39*a02);
  a38=(a38+a39);
  a17=(a17*a38);
  a25=(a25-a17);
  a25=(a13*a25);
  a23=(a23*a25);
  a23=(a23/a36);
  a23=(-a23);
  if (res[1]!=0) res[1][100]=a23;
  a00=(a00+a00);
  a23=(a13*a00);
  a23=(a14*a23);
  a23=(a23/a20);
  a23=(-a23);
  if (res[1]!=0) res[1][101]=a23;
  a01=(a01+a01);
  a23=(a13*a01);
  a23=(a14*a23);
  a23=(a23/a20);
  a23=(-a23);
  if (res[1]!=0) res[1][102]=a23;
  a08=(a01*a08);
  a12=(a00*a12);
  a08=(a08-a12);
  a08=(a13*a08);
  a08=(a14*a08);
  a08=(a08/a20);
  a08=(-a08);
  if (res[1]!=0) res[1][103]=a08;
  a09=(a00*a09);
  a30=(a01*a30);
  a09=(a09+a30);
  a09=(a13*a09);
  a09=(a14*a09);
  a09=(a09/a20);
  a09=(-a09);
  if (res[1]!=0) res[1][104]=a09;
  a35=(a00*a35);
  a10=(a01*a10);
  a35=(a35+a10);
  a35=(a13*a35);
  a35=(a14*a35);
  a35=(a35/a20);
  a35=(-a35);
  if (res[1]!=0) res[1][105]=a35;
  a04=(a01*a04);
  a38=(a00*a38);
  a04=(a04-a38);
  a04=(a13*a04);
  a04=(a14*a04);
  a04=(a04/a20);
  a04=(-a04);
  if (res[1]!=0) res[1][106]=a04;
  a00=(a41*a00);
  a00=(a13*a00);
  a00=(a14*a00);
  a00=(a00/a20);
  a00=(-a00);
  if (res[1]!=0) res[1][107]=a00;
  a41=(a41*a01);
  a13=(a13*a41);
  a14=(a14*a13);
  a14=(a14/a20);
  a14=(-a14);
  if (res[1]!=0) res[1][108]=a14;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_3cables_cost_y_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_3cables_cost_y_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_3cables_cost_y_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinodynamic_load_3cables_cost_y_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_3cables_cost_y_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinodynamic_load_3cables_cost_y_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void kinodynamic_load_3cables_cost_y_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void kinodynamic_load_3cables_cost_y_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int kinodynamic_load_3cables_cost_y_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int kinodynamic_load_3cables_cost_y_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real kinodynamic_load_3cables_cost_y_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinodynamic_load_3cables_cost_y_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinodynamic_load_3cables_cost_y_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinodynamic_load_3cables_cost_y_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinodynamic_load_3cables_cost_y_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_3cables_cost_y_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinodynamic_load_3cables_cost_y_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
